//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * CrossOrderCancelRequest can be found in Volume 4 of the specification
 *
 * <p>Java class for CrossOrderCancelRequest_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CrossOrderCancelRequest_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}CrossOrderCancelRequestElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}CrossOrderCancelRequestAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "CrossOrderCancelRequest_message_t",
  propOrder = {"pty", "sideCrossCxl", "instrmt", "undly", "leg"}
)
public class CrossOrderCancelRequestMessageT extends AbstractMessageT {

  @XmlElement(name = "Pty")
  protected List<RootPartiesBlockT> pty;

  @XmlElement(name = "SideCrossCxl", required = true)
  protected List<SideCrossOrdCxlGrpBlockT> sideCrossCxl;

  @XmlElement(name = "Instrmt", required = true)
  protected InstrumentBlockT instrmt;

  @XmlElement(name = "Undly")
  protected List<UndInstrmtGrpBlockT> undly;

  @XmlElement(name = "Leg")
  protected List<InstrmtLegGrpBlockT> leg;

  @XmlAttribute(name = "OrdID")
  protected String ordID;

  @XmlAttribute(name = "OrdReqID")
  protected BigInteger ordReqID;

  @XmlAttribute(name = "ID", required = true)
  protected String id;

  @XmlAttribute(name = "OrigID", required = true)
  protected String origID;

  @XmlAttribute(name = "HstCxID")
  protected String hstCxID;

  @XmlAttribute(name = "Typ", required = true)
  protected BigInteger typ;

  @XmlAttribute(name = "Priorty", required = true)
  protected BigInteger priorty;

  @XmlAttribute(name = "MktSegID")
  protected String mktSegID;

  @XmlAttribute(name = "TxnTm", required = true)
  protected XMLGregorianCalendar txnTm;

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RootPartiesBlockT }
   */
  public List<RootPartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<RootPartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the sideCrossCxl property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the sideCrossCxl property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSideCrossCxl().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link SideCrossOrdCxlGrpBlockT }
   */
  public List<SideCrossOrdCxlGrpBlockT> getSideCrossCxl() {
    if (sideCrossCxl == null) {
      sideCrossCxl = new ArrayList<SideCrossOrdCxlGrpBlockT>();
    }
    return this.sideCrossCxl;
  }

  /**
   * Gets the value of the instrmt property.
   *
   * @return possible object is {@link InstrumentBlockT }
   */
  public InstrumentBlockT getInstrmt() {
    return instrmt;
  }

  /**
   * Sets the value of the instrmt property.
   *
   * @param value allowed object is {@link InstrumentBlockT }
   */
  public void setInstrmt(InstrumentBlockT value) {
    this.instrmt = value;
  }

  /**
   * Gets the value of the undly property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the undly property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getUndly().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UndInstrmtGrpBlockT }
   */
  public List<UndInstrmtGrpBlockT> getUndly() {
    if (undly == null) {
      undly = new ArrayList<UndInstrmtGrpBlockT>();
    }
    return this.undly;
  }

  /**
   * Gets the value of the leg property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the leg property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getLeg().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link InstrmtLegGrpBlockT }
   */
  public List<InstrmtLegGrpBlockT> getLeg() {
    if (leg == null) {
      leg = new ArrayList<InstrmtLegGrpBlockT>();
    }
    return this.leg;
  }

  /**
   * Gets the value of the ordID property.
   *
   * @return possible object is {@link String }
   */
  public String getOrdID() {
    return ordID;
  }

  /**
   * Sets the value of the ordID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrdID(String value) {
    this.ordID = value;
  }

  /**
   * Gets the value of the ordReqID property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getOrdReqID() {
    return ordReqID;
  }

  /**
   * Sets the value of the ordReqID property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setOrdReqID(BigInteger value) {
    this.ordReqID = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the origID property.
   *
   * @return possible object is {@link String }
   */
  public String getOrigID() {
    return origID;
  }

  /**
   * Sets the value of the origID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrigID(String value) {
    this.origID = value;
  }

  /**
   * Gets the value of the hstCxID property.
   *
   * @return possible object is {@link String }
   */
  public String getHstCxID() {
    return hstCxID;
  }

  /**
   * Sets the value of the hstCxID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHstCxID(String value) {
    this.hstCxID = value;
  }

  /**
   * Gets the value of the typ property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTyp() {
    return typ;
  }

  /**
   * Sets the value of the typ property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTyp(BigInteger value) {
    this.typ = value;
  }

  /**
   * Gets the value of the priorty property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPriorty() {
    return priorty;
  }

  /**
   * Sets the value of the priorty property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPriorty(BigInteger value) {
    this.priorty = value;
  }

  /**
   * Gets the value of the mktSegID property.
   *
   * @return possible object is {@link String }
   */
  public String getMktSegID() {
    return mktSegID;
  }

  /**
   * Sets the value of the mktSegID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMktSegID(String value) {
    this.mktSegID = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }
}
