//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for FlexProductEligibilityGrp_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FlexProductEligibilityGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}FlexProductEligibilityGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}FlexProductEligibilityGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlexProductEligibilityGrp_Block_t")
public class FlexProductEligibilityGrpBlockT {

  @XmlAttribute(name = "FlexProdElig")
  protected String flexProdElig;

  @XmlAttribute(name = "FlexProdEligCmplx")
  protected String flexProdEligCmplx;

  /**
   * Gets the value of the flexProdElig property.
   *
   * @return possible object is {@link String }
   */
  public String getFlexProdElig() {
    return flexProdElig;
  }

  /**
   * Sets the value of the flexProdElig property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFlexProdElig(String value) {
    this.flexProdElig = value;
  }

  /**
   * Gets the value of the flexProdEligCmplx property.
   *
   * @return possible object is {@link String }
   */
  public String getFlexProdEligCmplx() {
    return flexProdEligCmplx;
  }

  /**
   * Sets the value of the flexProdEligCmplx property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFlexProdEligCmplx(String value) {
    this.flexProdEligCmplx = value;
  }
}
