//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * IOI can be found in Volume 3 of the specification
 *
 * <p>Java class for IOI_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IOI_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}IOIElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}IOIAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "IOI_message_t",
  propOrder = {
    "applSeqCtrl",
    "instrmt",
    "instrmtExt",
    "pty",
    "finDetls",
    "undly",
    "reltdInstrmt",
    "ordQty",
    "stip",
    "ioi",
    "pxQual",
    "qual",
    "rtg",
    "sprdBnchmkCurve",
    "reltvVal",
    "yield"
  }
)
public class IOIMessageT extends AbstractMessageT {

  @XmlElement(name = "ApplSeqCtrl")
  protected ApplicationSequenceControlBlockT applSeqCtrl;

  @XmlElement(name = "Instrmt", required = true)
  protected InstrumentBlockT instrmt;

  @XmlElement(name = "InstrmtExt")
  protected InstrumentExtensionBlockT instrmtExt;

  @XmlElement(name = "Pty")
  protected List<PartiesBlockT> pty;

  @XmlElement(name = "FinDetls")
  protected FinancingDetailsBlockT finDetls;

  @XmlElement(name = "Undly")
  protected List<UndInstrmtGrpBlockT> undly;

  @XmlElement(name = "ReltdInstrmt")
  protected List<RelatedInstrumentGrpBlockT> reltdInstrmt;

  @XmlElement(name = "OrdQty")
  protected OrderQtyDataBlockT ordQty;

  @XmlElement(name = "Stip")
  protected List<StipulationsBlockT> stip;

  @XmlElement(name = "IOI")
  protected List<InstrmtLegIOIGrpBlockT> ioi;

  @XmlElement(name = "PxQual")
  protected List<PriceQualifierGrpBlockT> pxQual;

  @XmlElement(name = "Qual")
  protected List<IOIQualGrpBlockT> qual;

  @XmlElement(name = "Rtg")
  protected List<RoutingGrpBlockT> rtg;

  @XmlElement(name = "SprdBnchmkCurve")
  protected SpreadOrBenchmarkCurveDataBlockT sprdBnchmkCurve;

  @XmlElement(name = "ReltvVal")
  protected List<RelativeValueGrpBlockT> reltvVal;

  @XmlElement(name = "Yield")
  protected YieldDataBlockT yield;

  @XmlAttribute(name = "ID", required = true)
  protected String id;

  @XmlAttribute(name = "TransTyp", required = true)
  protected IOITransTypeEnumT transTyp;

  @XmlAttribute(name = "RefID")
  protected String refID;

  @XmlAttribute(name = "Side", required = true)
  protected String side;

  @XmlAttribute(name = "QtyTyp")
  protected BigInteger qtyTyp;

  @XmlAttribute(name = "Qty", required = true)
  protected String qty;

  @XmlAttribute(name = "Ccy")
  protected String ccy;

  @XmlAttribute(name = "PxTyp")
  protected BigInteger pxTyp;

  @XmlAttribute(name = "Px")
  protected BigDecimal px;

  @XmlAttribute(name = "ValidUntilTm")
  protected XMLGregorianCalendar validUntilTm;

  @XmlAttribute(name = "QltyInd")
  protected IOIQltyIndEnumT qltyInd;

  @XmlAttribute(name = "NatFlag")
  protected IOINaturalFlagEnumT natFlag;

  @XmlAttribute(name = "Txt")
  protected String txt;

  @XmlAttribute(name = "EncTxtLen")
  protected BigInteger encTxtLen;

  @XmlAttribute(name = "EncTxt")
  protected byte[] encTxt;

  @XmlAttribute(name = "TxnTm")
  protected XMLGregorianCalendar txnTm;

  @XmlAttribute(name = "URL")
  protected String url;

  /**
   * Gets the value of the applSeqCtrl property.
   *
   * @return possible object is {@link ApplicationSequenceControlBlockT }
   */
  public ApplicationSequenceControlBlockT getApplSeqCtrl() {
    return applSeqCtrl;
  }

  /**
   * Sets the value of the applSeqCtrl property.
   *
   * @param value allowed object is {@link ApplicationSequenceControlBlockT }
   */
  public void setApplSeqCtrl(ApplicationSequenceControlBlockT value) {
    this.applSeqCtrl = value;
  }

  /**
   * Gets the value of the instrmt property.
   *
   * @return possible object is {@link InstrumentBlockT }
   */
  public InstrumentBlockT getInstrmt() {
    return instrmt;
  }

  /**
   * Sets the value of the instrmt property.
   *
   * @param value allowed object is {@link InstrumentBlockT }
   */
  public void setInstrmt(InstrumentBlockT value) {
    this.instrmt = value;
  }

  /**
   * Gets the value of the instrmtExt property.
   *
   * @return possible object is {@link InstrumentExtensionBlockT }
   */
  public InstrumentExtensionBlockT getInstrmtExt() {
    return instrmtExt;
  }

  /**
   * Sets the value of the instrmtExt property.
   *
   * @param value allowed object is {@link InstrumentExtensionBlockT }
   */
  public void setInstrmtExt(InstrumentExtensionBlockT value) {
    this.instrmtExt = value;
  }

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PartiesBlockT }
   */
  public List<PartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<PartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the finDetls property.
   *
   * @return possible object is {@link FinancingDetailsBlockT }
   */
  public FinancingDetailsBlockT getFinDetls() {
    return finDetls;
  }

  /**
   * Sets the value of the finDetls property.
   *
   * @param value allowed object is {@link FinancingDetailsBlockT }
   */
  public void setFinDetls(FinancingDetailsBlockT value) {
    this.finDetls = value;
  }

  /**
   * Gets the value of the undly property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the undly property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getUndly().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UndInstrmtGrpBlockT }
   */
  public List<UndInstrmtGrpBlockT> getUndly() {
    if (undly == null) {
      undly = new ArrayList<UndInstrmtGrpBlockT>();
    }
    return this.undly;
  }

  /**
   * Gets the value of the reltdInstrmt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the reltdInstrmt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getReltdInstrmt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RelatedInstrumentGrpBlockT }
   */
  public List<RelatedInstrumentGrpBlockT> getReltdInstrmt() {
    if (reltdInstrmt == null) {
      reltdInstrmt = new ArrayList<RelatedInstrumentGrpBlockT>();
    }
    return this.reltdInstrmt;
  }

  /**
   * Gets the value of the ordQty property.
   *
   * @return possible object is {@link OrderQtyDataBlockT }
   */
  public OrderQtyDataBlockT getOrdQty() {
    return ordQty;
  }

  /**
   * Sets the value of the ordQty property.
   *
   * @param value allowed object is {@link OrderQtyDataBlockT }
   */
  public void setOrdQty(OrderQtyDataBlockT value) {
    this.ordQty = value;
  }

  /**
   * Gets the value of the stip property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the stip property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getStip().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link StipulationsBlockT }
   */
  public List<StipulationsBlockT> getStip() {
    if (stip == null) {
      stip = new ArrayList<StipulationsBlockT>();
    }
    return this.stip;
  }

  /**
   * Gets the value of the ioi property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the ioi property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getIOI().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link InstrmtLegIOIGrpBlockT }
   */
  public List<InstrmtLegIOIGrpBlockT> getIOI() {
    if (ioi == null) {
      ioi = new ArrayList<InstrmtLegIOIGrpBlockT>();
    }
    return this.ioi;
  }

  /**
   * Gets the value of the pxQual property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pxQual property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPxQual().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PriceQualifierGrpBlockT }
   */
  public List<PriceQualifierGrpBlockT> getPxQual() {
    if (pxQual == null) {
      pxQual = new ArrayList<PriceQualifierGrpBlockT>();
    }
    return this.pxQual;
  }

  /**
   * Gets the value of the qual property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the qual property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getQual().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link IOIQualGrpBlockT }
   */
  public List<IOIQualGrpBlockT> getQual() {
    if (qual == null) {
      qual = new ArrayList<IOIQualGrpBlockT>();
    }
    return this.qual;
  }

  /**
   * Gets the value of the rtg property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the rtg property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRtg().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RoutingGrpBlockT }
   */
  public List<RoutingGrpBlockT> getRtg() {
    if (rtg == null) {
      rtg = new ArrayList<RoutingGrpBlockT>();
    }
    return this.rtg;
  }

  /**
   * Gets the value of the sprdBnchmkCurve property.
   *
   * @return possible object is {@link SpreadOrBenchmarkCurveDataBlockT }
   */
  public SpreadOrBenchmarkCurveDataBlockT getSprdBnchmkCurve() {
    return sprdBnchmkCurve;
  }

  /**
   * Sets the value of the sprdBnchmkCurve property.
   *
   * @param value allowed object is {@link SpreadOrBenchmarkCurveDataBlockT }
   */
  public void setSprdBnchmkCurve(SpreadOrBenchmarkCurveDataBlockT value) {
    this.sprdBnchmkCurve = value;
  }

  /**
   * Gets the value of the reltvVal property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the reltvVal property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getReltvVal().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RelativeValueGrpBlockT }
   */
  public List<RelativeValueGrpBlockT> getReltvVal() {
    if (reltvVal == null) {
      reltvVal = new ArrayList<RelativeValueGrpBlockT>();
    }
    return this.reltvVal;
  }

  /**
   * Gets the value of the yield property.
   *
   * @return possible object is {@link YieldDataBlockT }
   */
  public YieldDataBlockT getYield() {
    return yield;
  }

  /**
   * Sets the value of the yield property.
   *
   * @param value allowed object is {@link YieldDataBlockT }
   */
  public void setYield(YieldDataBlockT value) {
    this.yield = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the transTyp property.
   *
   * @return possible object is {@link IOITransTypeEnumT }
   */
  public IOITransTypeEnumT getTransTyp() {
    return transTyp;
  }

  /**
   * Sets the value of the transTyp property.
   *
   * @param value allowed object is {@link IOITransTypeEnumT }
   */
  public void setTransTyp(IOITransTypeEnumT value) {
    this.transTyp = value;
  }

  /**
   * Gets the value of the refID property.
   *
   * @return possible object is {@link String }
   */
  public String getRefID() {
    return refID;
  }

  /**
   * Sets the value of the refID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRefID(String value) {
    this.refID = value;
  }

  /**
   * Gets the value of the side property.
   *
   * @return possible object is {@link String }
   */
  public String getSide() {
    return side;
  }

  /**
   * Sets the value of the side property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSide(String value) {
    this.side = value;
  }

  /**
   * Gets the value of the qtyTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getQtyTyp() {
    return qtyTyp;
  }

  /**
   * Sets the value of the qtyTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setQtyTyp(BigInteger value) {
    this.qtyTyp = value;
  }

  /**
   * Gets the value of the qty property.
   *
   * @return possible object is {@link String }
   */
  public String getQty() {
    return qty;
  }

  /**
   * Sets the value of the qty property.
   *
   * @param value allowed object is {@link String }
   */
  public void setQty(String value) {
    this.qty = value;
  }

  /**
   * Gets the value of the ccy property.
   *
   * @return possible object is {@link String }
   */
  public String getCcy() {
    return ccy;
  }

  /**
   * Sets the value of the ccy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCcy(String value) {
    this.ccy = value;
  }

  /**
   * Gets the value of the pxTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPxTyp() {
    return pxTyp;
  }

  /**
   * Sets the value of the pxTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPxTyp(BigInteger value) {
    this.pxTyp = value;
  }

  /**
   * Gets the value of the px property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPx() {
    return px;
  }

  /**
   * Sets the value of the px property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPx(BigDecimal value) {
    this.px = value;
  }

  /**
   * Gets the value of the validUntilTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getValidUntilTm() {
    return validUntilTm;
  }

  /**
   * Sets the value of the validUntilTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setValidUntilTm(XMLGregorianCalendar value) {
    this.validUntilTm = value;
  }

  /**
   * Gets the value of the qltyInd property.
   *
   * @return possible object is {@link IOIQltyIndEnumT }
   */
  public IOIQltyIndEnumT getQltyInd() {
    return qltyInd;
  }

  /**
   * Sets the value of the qltyInd property.
   *
   * @param value allowed object is {@link IOIQltyIndEnumT }
   */
  public void setQltyInd(IOIQltyIndEnumT value) {
    this.qltyInd = value;
  }

  /**
   * Gets the value of the natFlag property.
   *
   * @return possible object is {@link IOINaturalFlagEnumT }
   */
  public IOINaturalFlagEnumT getNatFlag() {
    return natFlag;
  }

  /**
   * Sets the value of the natFlag property.
   *
   * @param value allowed object is {@link IOINaturalFlagEnumT }
   */
  public void setNatFlag(IOINaturalFlagEnumT value) {
    this.natFlag = value;
  }

  /**
   * Gets the value of the txt property.
   *
   * @return possible object is {@link String }
   */
  public String getTxt() {
    return txt;
  }

  /**
   * Sets the value of the txt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTxt(String value) {
    this.txt = value;
  }

  /**
   * Gets the value of the encTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncTxtLen() {
    return encTxtLen;
  }

  /**
   * Sets the value of the encTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncTxtLen(BigInteger value) {
    this.encTxtLen = value;
  }

  /**
   * Gets the value of the encTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncTxt() {
    return encTxt;
  }

  /**
   * Sets the value of the encTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncTxt(byte[] value) {
    this.encTxt = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }

  /**
   * Gets the value of the url property.
   *
   * @return possible object is {@link String }
   */
  public String getURL() {
    return url;
  }

  /**
   * Sets the value of the url property.
   *
   * @param value allowed object is {@link String }
   */
  public void setURL(String value) {
    this.url = value;
  }
}
