//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for LegComplexEventDates_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LegComplexEventDates_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}LegComplexEventDatesElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}LegComplexEventDatesAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "LegComplexEventDates_Block_t",
  propOrder = {"evntTms"}
)
public class LegComplexEventDatesBlockT {

  @XmlElement(name = "EvntTms")
  protected List<LegComplexEventTimesBlockT> evntTms;

  @XmlAttribute(name = "StartDt")
  protected XMLGregorianCalendar startDt;

  @XmlAttribute(name = "EndDt")
  protected XMLGregorianCalendar endDt;

  /**
   * Gets the value of the evntTms property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the evntTms property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getEvntTms().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link LegComplexEventTimesBlockT }
   */
  public List<LegComplexEventTimesBlockT> getEvntTms() {
    if (evntTms == null) {
      evntTms = new ArrayList<LegComplexEventTimesBlockT>();
    }
    return this.evntTms;
  }

  /**
   * Gets the value of the startDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getStartDt() {
    return startDt;
  }

  /**
   * Sets the value of the startDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setStartDt(XMLGregorianCalendar value) {
    this.startDt = value;
  }

  /**
   * Gets the value of the endDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getEndDt() {
    return endDt;
  }

  /**
   * Sets the value of the endDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setEndDt(XMLGregorianCalendar value) {
    this.endDt = value;
  }
}
