//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for MDStatisticParameters_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MDStatisticParameters_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}MDStatisticParametersElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}MDStatisticParametersAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "MDStatisticParameters_Block_t",
  propOrder = {"pty"}
)
public class MDStatisticParametersBlockT {

  @XmlElement(name = "Pty")
  protected List<NestedPartiesBlockT> pty;

  @XmlAttribute(name = "Typ", required = true)
  protected String typ;

  @XmlAttribute(name = "Scope", required = true)
  protected String scope;

  @XmlAttribute(name = "SubScope")
  protected String subScope;

  @XmlAttribute(name = "ScopeTyp")
  protected String scopeTyp;

  @XmlAttribute(name = "StatsNme")
  protected String statsNme;

  @XmlAttribute(name = "Desc")
  protected String desc;

  @XmlAttribute(name = "EncDescLen")
  protected BigInteger encDescLen;

  @XmlAttribute(name = "EncDesc")
  protected byte[] encDesc;

  @XmlAttribute(name = "MktDepth")
  protected BigInteger mktDepth;

  @XmlAttribute(name = "FreqPeriod")
  protected BigInteger freqPeriod;

  @XmlAttribute(name = "FreqUnit")
  protected BigInteger freqUnit;

  @XmlAttribute(name = "DelayPeriod")
  protected BigInteger delayPeriod;

  @XmlAttribute(name = "DelayUnit")
  protected BigInteger delayUnit;

  @XmlAttribute(name = "IntvlTyp", required = true)
  protected BigInteger intvlTyp;

  @XmlAttribute(name = "IntvlTypUnit")
  protected TimeUnitEnumT intvlTypUnit;

  @XmlAttribute(name = "IntvlPeriod")
  protected BigInteger intvlPeriod;

  @XmlAttribute(name = "IntvlUnit")
  protected BigInteger intvlUnit;

  @XmlAttribute(name = "StartDt")
  protected XMLGregorianCalendar startDt;

  @XmlAttribute(name = "EndDt")
  protected XMLGregorianCalendar endDt;

  @XmlAttribute(name = "StartTm")
  protected XMLGregorianCalendar startTm;

  @XmlAttribute(name = "EndTm")
  protected XMLGregorianCalendar endTm;

  @XmlAttribute(name = "RatioTyp")
  protected BigInteger ratioTyp;

  @XmlAttribute(name = "AnnlTrdgBizDays")
  protected BigInteger annlTrdgBizDays;

  @XmlAttribute(name = "TrdgCpcty")
  protected BigInteger trdgCpcty;

  @XmlAttribute(name = "OrdTyp")
  protected String ordTyp;

  @XmlAttribute(name = "TmInForce")
  protected String tmInForce;

  @XmlAttribute(name = "QCond")
  protected String qCond;

  @XmlAttribute(name = "TrdCond")
  protected String trdCond;

  @XmlAttribute(name = "Side")
  protected String side;

  @XmlAttribute(name = "InptSrc")
  protected String inptSrc;

  @XmlAttribute(name = "SesID")
  protected String sesID;

  @XmlAttribute(name = "SesSub")
  protected String sesSub;

  @XmlAttribute(name = "MDOrigTyp")
  protected BigInteger mdOrigTyp;

  @XmlAttribute(name = "Tier")
  protected BigInteger tier;

  @XmlAttribute(name = "Method")
  protected BigInteger method;

  @XmlAttribute(name = "MDFeedTyp")
  protected String mdFeedTyp;

  @XmlAttribute(name = "ExpsreDur")
  protected BigInteger expsreDur;

  @XmlAttribute(name = "ExpsreDurUnit")
  protected BigInteger expsreDurUnit;

  @XmlAttribute(name = "AgrsrInd")
  protected AggressorIndicatorEnumT agrsrInd;

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link NestedPartiesBlockT }
   */
  public List<NestedPartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<NestedPartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the typ property.
   *
   * @return possible object is {@link String }
   */
  public String getTyp() {
    return typ;
  }

  /**
   * Sets the value of the typ property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTyp(String value) {
    this.typ = value;
  }

  /**
   * Gets the value of the scope property.
   *
   * @return possible object is {@link String }
   */
  public String getScope() {
    return scope;
  }

  /**
   * Sets the value of the scope property.
   *
   * @param value allowed object is {@link String }
   */
  public void setScope(String value) {
    this.scope = value;
  }

  /**
   * Gets the value of the subScope property.
   *
   * @return possible object is {@link String }
   */
  public String getSubScope() {
    return subScope;
  }

  /**
   * Sets the value of the subScope property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubScope(String value) {
    this.subScope = value;
  }

  /**
   * Gets the value of the scopeTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getScopeTyp() {
    return scopeTyp;
  }

  /**
   * Sets the value of the scopeTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setScopeTyp(String value) {
    this.scopeTyp = value;
  }

  /**
   * Gets the value of the statsNme property.
   *
   * @return possible object is {@link String }
   */
  public String getStatsNme() {
    return statsNme;
  }

  /**
   * Sets the value of the statsNme property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStatsNme(String value) {
    this.statsNme = value;
  }

  /**
   * Gets the value of the desc property.
   *
   * @return possible object is {@link String }
   */
  public String getDesc() {
    return desc;
  }

  /**
   * Sets the value of the desc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDesc(String value) {
    this.desc = value;
  }

  /**
   * Gets the value of the encDescLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncDescLen() {
    return encDescLen;
  }

  /**
   * Sets the value of the encDescLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncDescLen(BigInteger value) {
    this.encDescLen = value;
  }

  /**
   * Gets the value of the encDesc property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncDesc() {
    return encDesc;
  }

  /**
   * Sets the value of the encDesc property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncDesc(byte[] value) {
    this.encDesc = value;
  }

  /**
   * Gets the value of the mktDepth property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMktDepth() {
    return mktDepth;
  }

  /**
   * Sets the value of the mktDepth property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMktDepth(BigInteger value) {
    this.mktDepth = value;
  }

  /**
   * Gets the value of the freqPeriod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getFreqPeriod() {
    return freqPeriod;
  }

  /**
   * Sets the value of the freqPeriod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setFreqPeriod(BigInteger value) {
    this.freqPeriod = value;
  }

  /**
   * Gets the value of the freqUnit property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getFreqUnit() {
    return freqUnit;
  }

  /**
   * Sets the value of the freqUnit property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setFreqUnit(BigInteger value) {
    this.freqUnit = value;
  }

  /**
   * Gets the value of the delayPeriod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getDelayPeriod() {
    return delayPeriod;
  }

  /**
   * Sets the value of the delayPeriod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setDelayPeriod(BigInteger value) {
    this.delayPeriod = value;
  }

  /**
   * Gets the value of the delayUnit property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getDelayUnit() {
    return delayUnit;
  }

  /**
   * Sets the value of the delayUnit property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setDelayUnit(BigInteger value) {
    this.delayUnit = value;
  }

  /**
   * Gets the value of the intvlTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getIntvlTyp() {
    return intvlTyp;
  }

  /**
   * Sets the value of the intvlTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setIntvlTyp(BigInteger value) {
    this.intvlTyp = value;
  }

  /**
   * Gets the value of the intvlTypUnit property.
   *
   * @return possible object is {@link TimeUnitEnumT }
   */
  public TimeUnitEnumT getIntvlTypUnit() {
    return intvlTypUnit;
  }

  /**
   * Sets the value of the intvlTypUnit property.
   *
   * @param value allowed object is {@link TimeUnitEnumT }
   */
  public void setIntvlTypUnit(TimeUnitEnumT value) {
    this.intvlTypUnit = value;
  }

  /**
   * Gets the value of the intvlPeriod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getIntvlPeriod() {
    return intvlPeriod;
  }

  /**
   * Sets the value of the intvlPeriod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setIntvlPeriod(BigInteger value) {
    this.intvlPeriod = value;
  }

  /**
   * Gets the value of the intvlUnit property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getIntvlUnit() {
    return intvlUnit;
  }

  /**
   * Sets the value of the intvlUnit property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setIntvlUnit(BigInteger value) {
    this.intvlUnit = value;
  }

  /**
   * Gets the value of the startDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getStartDt() {
    return startDt;
  }

  /**
   * Sets the value of the startDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setStartDt(XMLGregorianCalendar value) {
    this.startDt = value;
  }

  /**
   * Gets the value of the endDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getEndDt() {
    return endDt;
  }

  /**
   * Sets the value of the endDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setEndDt(XMLGregorianCalendar value) {
    this.endDt = value;
  }

  /**
   * Gets the value of the startTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getStartTm() {
    return startTm;
  }

  /**
   * Sets the value of the startTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setStartTm(XMLGregorianCalendar value) {
    this.startTm = value;
  }

  /**
   * Gets the value of the endTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getEndTm() {
    return endTm;
  }

  /**
   * Sets the value of the endTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setEndTm(XMLGregorianCalendar value) {
    this.endTm = value;
  }

  /**
   * Gets the value of the ratioTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRatioTyp() {
    return ratioTyp;
  }

  /**
   * Sets the value of the ratioTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRatioTyp(BigInteger value) {
    this.ratioTyp = value;
  }

  /**
   * Gets the value of the annlTrdgBizDays property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getAnnlTrdgBizDays() {
    return annlTrdgBizDays;
  }

  /**
   * Sets the value of the annlTrdgBizDays property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setAnnlTrdgBizDays(BigInteger value) {
    this.annlTrdgBizDays = value;
  }

  /**
   * Gets the value of the trdgCpcty property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTrdgCpcty() {
    return trdgCpcty;
  }

  /**
   * Sets the value of the trdgCpcty property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTrdgCpcty(BigInteger value) {
    this.trdgCpcty = value;
  }

  /**
   * Gets the value of the ordTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getOrdTyp() {
    return ordTyp;
  }

  /**
   * Sets the value of the ordTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrdTyp(String value) {
    this.ordTyp = value;
  }

  /**
   * Gets the value of the tmInForce property.
   *
   * @return possible object is {@link String }
   */
  public String getTmInForce() {
    return tmInForce;
  }

  /**
   * Sets the value of the tmInForce property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTmInForce(String value) {
    this.tmInForce = value;
  }

  /**
   * Gets the value of the qCond property.
   *
   * @return possible object is {@link String }
   */
  public String getQCond() {
    return qCond;
  }

  /**
   * Sets the value of the qCond property.
   *
   * @param value allowed object is {@link String }
   */
  public void setQCond(String value) {
    this.qCond = value;
  }

  /**
   * Gets the value of the trdCond property.
   *
   * @return possible object is {@link String }
   */
  public String getTrdCond() {
    return trdCond;
  }

  /**
   * Sets the value of the trdCond property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTrdCond(String value) {
    this.trdCond = value;
  }

  /**
   * Gets the value of the side property.
   *
   * @return possible object is {@link String }
   */
  public String getSide() {
    return side;
  }

  /**
   * Sets the value of the side property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSide(String value) {
    this.side = value;
  }

  /**
   * Gets the value of the inptSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getInptSrc() {
    return inptSrc;
  }

  /**
   * Sets the value of the inptSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setInptSrc(String value) {
    this.inptSrc = value;
  }

  /**
   * Gets the value of the sesID property.
   *
   * @return possible object is {@link String }
   */
  public String getSesID() {
    return sesID;
  }

  /**
   * Sets the value of the sesID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSesID(String value) {
    this.sesID = value;
  }

  /**
   * Gets the value of the sesSub property.
   *
   * @return possible object is {@link String }
   */
  public String getSesSub() {
    return sesSub;
  }

  /**
   * Sets the value of the sesSub property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSesSub(String value) {
    this.sesSub = value;
  }

  /**
   * Gets the value of the mdOrigTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMDOrigTyp() {
    return mdOrigTyp;
  }

  /**
   * Sets the value of the mdOrigTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMDOrigTyp(BigInteger value) {
    this.mdOrigTyp = value;
  }

  /**
   * Gets the value of the tier property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTier() {
    return tier;
  }

  /**
   * Sets the value of the tier property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTier(BigInteger value) {
    this.tier = value;
  }

  /**
   * Gets the value of the method property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMethod() {
    return method;
  }

  /**
   * Sets the value of the method property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMethod(BigInteger value) {
    this.method = value;
  }

  /**
   * Gets the value of the mdFeedTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getMDFeedTyp() {
    return mdFeedTyp;
  }

  /**
   * Sets the value of the mdFeedTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMDFeedTyp(String value) {
    this.mdFeedTyp = value;
  }

  /**
   * Gets the value of the expsreDur property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getExpsreDur() {
    return expsreDur;
  }

  /**
   * Sets the value of the expsreDur property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setExpsreDur(BigInteger value) {
    this.expsreDur = value;
  }

  /**
   * Gets the value of the expsreDurUnit property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getExpsreDurUnit() {
    return expsreDurUnit;
  }

  /**
   * Sets the value of the expsreDurUnit property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setExpsreDurUnit(BigInteger value) {
    this.expsreDurUnit = value;
  }

  /**
   * Gets the value of the agrsrInd property.
   *
   * @return possible object is {@link AggressorIndicatorEnumT }
   */
  public AggressorIndicatorEnumT getAgrsrInd() {
    return agrsrInd;
  }

  /**
   * Sets the value of the agrsrInd property.
   *
   * @param value allowed object is {@link AggressorIndicatorEnumT }
   */
  public void setAgrsrInd(AggressorIndicatorEnumT value) {
    this.agrsrInd = value;
  }
}
