//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * Java class for MDStatisticRptGrp_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MDStatisticRptGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}MDStatisticRptGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}MDStatisticRptGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "MDStatisticRptGrp_Block_t",
  propOrder = {"statsPrm"}
)
public class MDStatisticRptGrpBlockT {

  @XmlElement(name = "StatsPrm")
  protected MDStatisticParametersBlockT statsPrm;

  @XmlAttribute(name = "StatsID")
  protected String statsID;

  @XmlAttribute(name = "Tm")
  protected XMLGregorianCalendar tm;

  @XmlAttribute(name = "Stat")
  protected BigInteger stat;

  @XmlAttribute(name = "Val")
  protected BigDecimal val;

  @XmlAttribute(name = "Typ")
  protected BigInteger typ;

  @XmlAttribute(name = "ValUnit")
  protected BigInteger valUnit;

  /**
   * Gets the value of the statsPrm property.
   *
   * @return possible object is {@link MDStatisticParametersBlockT }
   */
  public MDStatisticParametersBlockT getStatsPrm() {
    return statsPrm;
  }

  /**
   * Sets the value of the statsPrm property.
   *
   * @param value allowed object is {@link MDStatisticParametersBlockT }
   */
  public void setStatsPrm(MDStatisticParametersBlockT value) {
    this.statsPrm = value;
  }

  /**
   * Gets the value of the statsID property.
   *
   * @return possible object is {@link String }
   */
  public String getStatsID() {
    return statsID;
  }

  /**
   * Sets the value of the statsID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStatsID(String value) {
    this.statsID = value;
  }

  /**
   * Gets the value of the tm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTm() {
    return tm;
  }

  /**
   * Sets the value of the tm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTm(XMLGregorianCalendar value) {
    this.tm = value;
  }

  /**
   * Gets the value of the stat property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getStat() {
    return stat;
  }

  /**
   * Sets the value of the stat property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setStat(BigInteger value) {
    this.stat = value;
  }

  /**
   * Gets the value of the val property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getVal() {
    return val;
  }

  /**
   * Sets the value of the val property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setVal(BigDecimal value) {
    this.val = value;
  }

  /**
   * Gets the value of the typ property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTyp() {
    return typ;
  }

  /**
   * Sets the value of the typ property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTyp(BigInteger value) {
    this.typ = value;
  }

  /**
   * Gets the value of the valUnit property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getValUnit() {
    return valUnit;
  }

  /**
   * Sets the value of the valUnit property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setValUnit(BigInteger value) {
    this.valUnit = value;
  }
}
