//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * PartyRiskLimitsReport can be found in Volume 3 of the specification
 *
 * <p>Java class for PartyRiskLimitsReport_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PartyRiskLimitsReport_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PartyRiskLimitsReportElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PartyRiskLimitsReportAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "PartyRiskLimitsReport_message_t",
  propOrder = {"applSeqCtrl", "ptyRiskLmt"}
)
public class PartyRiskLimitsReportMessageT extends AbstractMessageT {

  @XmlElement(name = "ApplSeqCtrl")
  protected ApplicationSequenceControlBlockT applSeqCtrl;

  @XmlElement(name = "PtyRiskLmt")
  protected List<PartyRiskLimitsGrpBlockT> ptyRiskLmt;

  @XmlAttribute(name = "RptID", required = true)
  protected String rptID;

  @XmlAttribute(name = "ReqID")
  protected String reqID;

  @XmlAttribute(name = "ReqTyp")
  protected BigInteger reqTyp;

  @XmlAttribute(name = "ReqRslt")
  protected String reqRslt;

  @XmlAttribute(name = "Unsol")
  protected UnsolicitedIndicatorEnumT unsol;

  @XmlAttribute(name = "TotNoPtys")
  protected BigInteger totNoPtys;

  @XmlAttribute(name = "LastFragment")
  protected LastFragmentEnumT lastFragment;

  @XmlAttribute(name = "TxnTm")
  protected XMLGregorianCalendar txnTm;

  @XmlAttribute(name = "Txt")
  protected String txt;

  @XmlAttribute(name = "EncTxtLen")
  protected BigInteger encTxtLen;

  @XmlAttribute(name = "EncTxt")
  protected byte[] encTxt;

  @XmlAttribute(name = "RejTxt")
  protected String rejTxt;

  @XmlAttribute(name = "EncRejTxtLen")
  protected BigInteger encRejTxtLen;

  @XmlAttribute(name = "EncRejTxt")
  protected byte[] encRejTxt;

  /**
   * Gets the value of the applSeqCtrl property.
   *
   * @return possible object is {@link ApplicationSequenceControlBlockT }
   */
  public ApplicationSequenceControlBlockT getApplSeqCtrl() {
    return applSeqCtrl;
  }

  /**
   * Sets the value of the applSeqCtrl property.
   *
   * @param value allowed object is {@link ApplicationSequenceControlBlockT }
   */
  public void setApplSeqCtrl(ApplicationSequenceControlBlockT value) {
    this.applSeqCtrl = value;
  }

  /**
   * Gets the value of the ptyRiskLmt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the ptyRiskLmt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPtyRiskLmt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PartyRiskLimitsGrpBlockT }
   */
  public List<PartyRiskLimitsGrpBlockT> getPtyRiskLmt() {
    if (ptyRiskLmt == null) {
      ptyRiskLmt = new ArrayList<PartyRiskLimitsGrpBlockT>();
    }
    return this.ptyRiskLmt;
  }

  /**
   * Gets the value of the rptID property.
   *
   * @return possible object is {@link String }
   */
  public String getRptID() {
    return rptID;
  }

  /**
   * Sets the value of the rptID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRptID(String value) {
    this.rptID = value;
  }

  /**
   * Gets the value of the reqID property.
   *
   * @return possible object is {@link String }
   */
  public String getReqID() {
    return reqID;
  }

  /**
   * Sets the value of the reqID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReqID(String value) {
    this.reqID = value;
  }

  /**
   * Gets the value of the reqTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getReqTyp() {
    return reqTyp;
  }

  /**
   * Sets the value of the reqTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setReqTyp(BigInteger value) {
    this.reqTyp = value;
  }

  /**
   * Gets the value of the reqRslt property.
   *
   * @return possible object is {@link String }
   */
  public String getReqRslt() {
    return reqRslt;
  }

  /**
   * Sets the value of the reqRslt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReqRslt(String value) {
    this.reqRslt = value;
  }

  /**
   * Gets the value of the unsol property.
   *
   * @return possible object is {@link UnsolicitedIndicatorEnumT }
   */
  public UnsolicitedIndicatorEnumT getUnsol() {
    return unsol;
  }

  /**
   * Sets the value of the unsol property.
   *
   * @param value allowed object is {@link UnsolicitedIndicatorEnumT }
   */
  public void setUnsol(UnsolicitedIndicatorEnumT value) {
    this.unsol = value;
  }

  /**
   * Gets the value of the totNoPtys property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTotNoPtys() {
    return totNoPtys;
  }

  /**
   * Sets the value of the totNoPtys property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTotNoPtys(BigInteger value) {
    this.totNoPtys = value;
  }

  /**
   * Gets the value of the lastFragment property.
   *
   * @return possible object is {@link LastFragmentEnumT }
   */
  public LastFragmentEnumT getLastFragment() {
    return lastFragment;
  }

  /**
   * Sets the value of the lastFragment property.
   *
   * @param value allowed object is {@link LastFragmentEnumT }
   */
  public void setLastFragment(LastFragmentEnumT value) {
    this.lastFragment = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }

  /**
   * Gets the value of the txt property.
   *
   * @return possible object is {@link String }
   */
  public String getTxt() {
    return txt;
  }

  /**
   * Sets the value of the txt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTxt(String value) {
    this.txt = value;
  }

  /**
   * Gets the value of the encTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncTxtLen() {
    return encTxtLen;
  }

  /**
   * Sets the value of the encTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncTxtLen(BigInteger value) {
    this.encTxtLen = value;
  }

  /**
   * Gets the value of the encTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncTxt() {
    return encTxt;
  }

  /**
   * Sets the value of the encTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncTxt(byte[] value) {
    this.encTxt = value;
  }

  /**
   * Gets the value of the rejTxt property.
   *
   * @return possible object is {@link String }
   */
  public String getRejTxt() {
    return rejTxt;
  }

  /**
   * Sets the value of the rejTxt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRejTxt(String value) {
    this.rejTxt = value;
  }

  /**
   * Gets the value of the encRejTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncRejTxtLen() {
    return encRejTxtLen;
  }

  /**
   * Sets the value of the encRejTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncRejTxtLen(BigInteger value) {
    this.encRejTxtLen = value;
  }

  /**
   * Gets the value of the encRejTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncRejTxt() {
    return encRejTxt;
  }

  /**
   * Sets the value of the encRejTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncRejTxt(byte[] value) {
    this.encRejTxt = value;
  }
}
