//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * PositionTransferInstruction can be found in Volume 5 of the specification
 *
 * <p>Java class for PositionTransferInstruction_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PositionTransferInstruction_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PositionTransferInstructionElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PositionTransferInstructionAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "PositionTransferInstruction_message_t",
  propOrder = {"pty", "tgtPty", "instrmt", "undly", "qty", "amt"}
)
public class PositionTransferInstructionMessageT extends AbstractMessageT {

  @XmlElement(name = "Pty")
  protected List<PartiesBlockT> pty;

  @XmlElement(name = "TgtPty", required = true)
  protected List<TargetPartiesBlockT> tgtPty;

  @XmlElement(name = "Instrmt")
  protected InstrumentBlockT instrmt;

  @XmlElement(name = "Undly")
  protected List<UndInstrmtGrpBlockT> undly;

  @XmlElement(name = "Qty")
  protected List<PositionQtyBlockT> qty;

  @XmlElement(name = "Amt")
  protected List<PositionAmountDataBlockT> amt;

  @XmlAttribute(name = "InstID", required = true)
  protected String instID;

  @XmlAttribute(name = "XferID")
  protected String xferID;

  @XmlAttribute(name = "TransTyp")
  protected BigInteger transTyp;

  @XmlAttribute(name = "XferTyp")
  protected BigInteger xferTyp;

  @XmlAttribute(name = "XferScope")
  protected BigInteger xferScope;

  @XmlAttribute(name = "BizDt")
  protected XMLGregorianCalendar bizDt;

  @XmlAttribute(name = "TrdDt")
  protected XMLGregorianCalendar trdDt;

  @XmlAttribute(name = "TxnTm")
  protected XMLGregorianCalendar txnTm;

  @XmlAttribute(name = "ClrTrdPx")
  protected BigDecimal clrTrdPx;

  @XmlAttribute(name = "Ccy")
  protected String ccy;

  @XmlAttribute(name = "PxTyp")
  protected BigInteger pxTyp;

  @XmlAttribute(name = "Txt")
  protected String txt;

  @XmlAttribute(name = "EncTxtLen")
  protected BigInteger encTxtLen;

  @XmlAttribute(name = "EncTxt")
  protected byte[] encTxt;

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PartiesBlockT }
   */
  public List<PartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<PartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the tgtPty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the tgtPty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTgtPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TargetPartiesBlockT }
   */
  public List<TargetPartiesBlockT> getTgtPty() {
    if (tgtPty == null) {
      tgtPty = new ArrayList<TargetPartiesBlockT>();
    }
    return this.tgtPty;
  }

  /**
   * Gets the value of the instrmt property.
   *
   * @return possible object is {@link InstrumentBlockT }
   */
  public InstrumentBlockT getInstrmt() {
    return instrmt;
  }

  /**
   * Sets the value of the instrmt property.
   *
   * @param value allowed object is {@link InstrumentBlockT }
   */
  public void setInstrmt(InstrumentBlockT value) {
    this.instrmt = value;
  }

  /**
   * Gets the value of the undly property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the undly property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getUndly().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UndInstrmtGrpBlockT }
   */
  public List<UndInstrmtGrpBlockT> getUndly() {
    if (undly == null) {
      undly = new ArrayList<UndInstrmtGrpBlockT>();
    }
    return this.undly;
  }

  /**
   * Gets the value of the qty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the qty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getQty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PositionQtyBlockT }
   */
  public List<PositionQtyBlockT> getQty() {
    if (qty == null) {
      qty = new ArrayList<PositionQtyBlockT>();
    }
    return this.qty;
  }

  /**
   * Gets the value of the amt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the amt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAmt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PositionAmountDataBlockT }
   */
  public List<PositionAmountDataBlockT> getAmt() {
    if (amt == null) {
      amt = new ArrayList<PositionAmountDataBlockT>();
    }
    return this.amt;
  }

  /**
   * Gets the value of the instID property.
   *
   * @return possible object is {@link String }
   */
  public String getInstID() {
    return instID;
  }

  /**
   * Sets the value of the instID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setInstID(String value) {
    this.instID = value;
  }

  /**
   * Gets the value of the xferID property.
   *
   * @return possible object is {@link String }
   */
  public String getXferID() {
    return xferID;
  }

  /**
   * Sets the value of the xferID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setXferID(String value) {
    this.xferID = value;
  }

  /**
   * Gets the value of the transTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTransTyp() {
    return transTyp;
  }

  /**
   * Sets the value of the transTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTransTyp(BigInteger value) {
    this.transTyp = value;
  }

  /**
   * Gets the value of the xferTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getXferTyp() {
    return xferTyp;
  }

  /**
   * Sets the value of the xferTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setXferTyp(BigInteger value) {
    this.xferTyp = value;
  }

  /**
   * Gets the value of the xferScope property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getXferScope() {
    return xferScope;
  }

  /**
   * Sets the value of the xferScope property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setXferScope(BigInteger value) {
    this.xferScope = value;
  }

  /**
   * Gets the value of the bizDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getBizDt() {
    return bizDt;
  }

  /**
   * Sets the value of the bizDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setBizDt(XMLGregorianCalendar value) {
    this.bizDt = value;
  }

  /**
   * Gets the value of the trdDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTrdDt() {
    return trdDt;
  }

  /**
   * Sets the value of the trdDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTrdDt(XMLGregorianCalendar value) {
    this.trdDt = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }

  /**
   * Gets the value of the clrTrdPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getClrTrdPx() {
    return clrTrdPx;
  }

  /**
   * Sets the value of the clrTrdPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setClrTrdPx(BigDecimal value) {
    this.clrTrdPx = value;
  }

  /**
   * Gets the value of the ccy property.
   *
   * @return possible object is {@link String }
   */
  public String getCcy() {
    return ccy;
  }

  /**
   * Sets the value of the ccy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCcy(String value) {
    this.ccy = value;
  }

  /**
   * Gets the value of the pxTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPxTyp() {
    return pxTyp;
  }

  /**
   * Sets the value of the pxTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPxTyp(BigInteger value) {
    this.pxTyp = value;
  }

  /**
   * Gets the value of the txt property.
   *
   * @return possible object is {@link String }
   */
  public String getTxt() {
    return txt;
  }

  /**
   * Sets the value of the txt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTxt(String value) {
    this.txt = value;
  }

  /**
   * Gets the value of the encTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncTxtLen() {
    return encTxtLen;
  }

  /**
   * Sets the value of the encTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncTxtLen(BigInteger value) {
    this.encTxtLen = value;
  }

  /**
   * Gets the value of the encTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncTxt() {
    return encTxt;
  }

  /**
   * Sets the value of the encTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncTxt(byte[] value) {
    this.encTxt = value;
  }
}
