//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * PositionTransferInstructionAck can be found in Volume 5 of the specification
 *
 * <p>Java class for PositionTransferInstructionAck_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PositionTransferInstructionAck_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PositionTransferInstructionAckElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}PositionTransferInstructionAckAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "PositionTransferInstructionAck_message_t",
  propOrder = {"pty", "tgtPty"}
)
public class PositionTransferInstructionAckMessageT extends AbstractMessageT {

  @XmlElement(name = "Pty")
  protected List<PartiesBlockT> pty;

  @XmlElement(name = "TgtPty")
  protected List<TargetPartiesBlockT> tgtPty;

  @XmlAttribute(name = "InstID", required = true)
  protected String instID;

  @XmlAttribute(name = "XferID")
  protected String xferID;

  @XmlAttribute(name = "TransTyp")
  protected BigInteger transTyp;

  @XmlAttribute(name = "XferTyp")
  protected BigInteger xferTyp;

  @XmlAttribute(name = "XferStat")
  protected BigInteger xferStat;

  @XmlAttribute(name = "RejRsn")
  protected String rejRsn;

  @XmlAttribute(name = "XferScope")
  protected BigInteger xferScope;

  @XmlAttribute(name = "TxnTm")
  protected XMLGregorianCalendar txnTm;

  @XmlAttribute(name = "RejTxt")
  protected String rejTxt;

  @XmlAttribute(name = "EncRejTxtLen")
  protected BigInteger encRejTxtLen;

  @XmlAttribute(name = "EncRejTxt")
  protected byte[] encRejTxt;

  @XmlAttribute(name = "Txt")
  protected String txt;

  @XmlAttribute(name = "EncTxtLen")
  protected BigInteger encTxtLen;

  @XmlAttribute(name = "EncTxt")
  protected byte[] encTxt;

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link PartiesBlockT }
   */
  public List<PartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<PartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the tgtPty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the tgtPty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTgtPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TargetPartiesBlockT }
   */
  public List<TargetPartiesBlockT> getTgtPty() {
    if (tgtPty == null) {
      tgtPty = new ArrayList<TargetPartiesBlockT>();
    }
    return this.tgtPty;
  }

  /**
   * Gets the value of the instID property.
   *
   * @return possible object is {@link String }
   */
  public String getInstID() {
    return instID;
  }

  /**
   * Sets the value of the instID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setInstID(String value) {
    this.instID = value;
  }

  /**
   * Gets the value of the xferID property.
   *
   * @return possible object is {@link String }
   */
  public String getXferID() {
    return xferID;
  }

  /**
   * Sets the value of the xferID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setXferID(String value) {
    this.xferID = value;
  }

  /**
   * Gets the value of the transTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTransTyp() {
    return transTyp;
  }

  /**
   * Sets the value of the transTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTransTyp(BigInteger value) {
    this.transTyp = value;
  }

  /**
   * Gets the value of the xferTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getXferTyp() {
    return xferTyp;
  }

  /**
   * Sets the value of the xferTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setXferTyp(BigInteger value) {
    this.xferTyp = value;
  }

  /**
   * Gets the value of the xferStat property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getXferStat() {
    return xferStat;
  }

  /**
   * Sets the value of the xferStat property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setXferStat(BigInteger value) {
    this.xferStat = value;
  }

  /**
   * Gets the value of the rejRsn property.
   *
   * @return possible object is {@link String }
   */
  public String getRejRsn() {
    return rejRsn;
  }

  /**
   * Sets the value of the rejRsn property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRejRsn(String value) {
    this.rejRsn = value;
  }

  /**
   * Gets the value of the xferScope property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getXferScope() {
    return xferScope;
  }

  /**
   * Sets the value of the xferScope property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setXferScope(BigInteger value) {
    this.xferScope = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }

  /**
   * Gets the value of the rejTxt property.
   *
   * @return possible object is {@link String }
   */
  public String getRejTxt() {
    return rejTxt;
  }

  /**
   * Sets the value of the rejTxt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRejTxt(String value) {
    this.rejTxt = value;
  }

  /**
   * Gets the value of the encRejTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncRejTxtLen() {
    return encRejTxtLen;
  }

  /**
   * Sets the value of the encRejTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncRejTxtLen(BigInteger value) {
    this.encRejTxtLen = value;
  }

  /**
   * Gets the value of the encRejTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncRejTxt() {
    return encRejTxt;
  }

  /**
   * Sets the value of the encRejTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncRejTxt(byte[] value) {
    this.encRejTxt = value;
  }

  /**
   * Gets the value of the txt property.
   *
   * @return possible object is {@link String }
   */
  public String getTxt() {
    return txt;
  }

  /**
   * Sets the value of the txt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTxt(String value) {
    this.txt = value;
  }

  /**
   * Gets the value of the encTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncTxtLen() {
    return encTxtLen;
  }

  /**
   * Sets the value of the encTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncTxtLen(BigInteger value) {
    this.encTxtLen = value;
  }

  /**
   * Gets the value of the encTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncTxt() {
    return encTxt;
  }

  /**
   * Sets the value of the encTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncTxt(byte[] value) {
    this.encTxt = value;
  }
}
