//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;

/**
 * Java class for QuoteSizeRuleGrp_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="QuoteSizeRuleGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}QuoteSizeRuleGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}QuoteSizeRuleGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuoteSizeRuleGrp_Block_t")
public class QuoteSizeRuleGrpBlockT {

  @XmlAttribute(name = "MinBidSz")
  protected BigDecimal minBidSz;

  @XmlAttribute(name = "MinOfrSz")
  protected BigDecimal minOfrSz;

  @XmlAttribute(name = "FastMktInd")
  protected String fastMktInd;

  /**
   * Gets the value of the minBidSz property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getMinBidSz() {
    return minBidSz;
  }

  /**
   * Sets the value of the minBidSz property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setMinBidSz(BigDecimal value) {
    this.minBidSz = value;
  }

  /**
   * Gets the value of the minOfrSz property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getMinOfrSz() {
    return minOfrSz;
  }

  /**
   * Sets the value of the minOfrSz property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setMinOfrSz(BigDecimal value) {
    this.minOfrSz = value;
  }

  /**
   * Gets the value of the fastMktInd property.
   *
   * @return possible object is {@link String }
   */
  public String getFastMktInd() {
    return fastMktInd;
  }

  /**
   * Sets the value of the fastMktInd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFastMktInd(String value) {
    this.fastMktInd = value;
  }
}
