//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;

/**
 * Java class for RelatedInstrumentGrp_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RelatedInstrumentGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}RelatedInstrumentGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}RelatedInstrumentGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedInstrumentGrp_Block_t")
public class RelatedInstrumentGrpBlockT {

  @XmlAttribute(name = "InstrmtTyp")
  protected BigInteger instrmtTyp;

  @XmlAttribute(name = "Sym")
  protected String sym;

  @XmlAttribute(name = "ID")
  protected String id;

  @XmlAttribute(name = "Src")
  protected String src;

  @XmlAttribute(name = "SecTyp")
  protected String secTyp;

  @XmlAttribute(name = "MMY")
  protected String mmy;

  @XmlAttribute(name = "ReltdID")
  protected String reltdID;

  @XmlAttribute(name = "ReltdIDSrc")
  protected String reltdIDSrc;

  @XmlAttribute(name = "ReltdStrmXIDRef")
  @XmlIDREF
  protected Object reltdStrmXIDRef;

  @XmlAttribute(name = "XIDRef")
  @XmlIDREF
  protected Object xidRef;

  /**
   * Gets the value of the instrmtTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getInstrmtTyp() {
    return instrmtTyp;
  }

  /**
   * Sets the value of the instrmtTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setInstrmtTyp(BigInteger value) {
    this.instrmtTyp = value;
  }

  /**
   * Gets the value of the sym property.
   *
   * @return possible object is {@link String }
   */
  public String getSym() {
    return sym;
  }

  /**
   * Sets the value of the sym property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSym(String value) {
    this.sym = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the src property.
   *
   * @return possible object is {@link String }
   */
  public String getSrc() {
    return src;
  }

  /**
   * Sets the value of the src property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSrc(String value) {
    this.src = value;
  }

  /**
   * Gets the value of the secTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getSecTyp() {
    return secTyp;
  }

  /**
   * Sets the value of the secTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSecTyp(String value) {
    this.secTyp = value;
  }

  /**
   * Gets the value of the mmy property.
   *
   * @return possible object is {@link String }
   */
  public String getMMY() {
    return mmy;
  }

  /**
   * Sets the value of the mmy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMMY(String value) {
    this.mmy = value;
  }

  /**
   * Gets the value of the reltdID property.
   *
   * @return possible object is {@link String }
   */
  public String getReltdID() {
    return reltdID;
  }

  /**
   * Sets the value of the reltdID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReltdID(String value) {
    this.reltdID = value;
  }

  /**
   * Gets the value of the reltdIDSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getReltdIDSrc() {
    return reltdIDSrc;
  }

  /**
   * Sets the value of the reltdIDSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReltdIDSrc(String value) {
    this.reltdIDSrc = value;
  }

  /**
   * Gets the value of the reltdStrmXIDRef property.
   *
   * @return possible object is {@link Object }
   */
  public Object getReltdStrmXIDRef() {
    return reltdStrmXIDRef;
  }

  /**
   * Sets the value of the reltdStrmXIDRef property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setReltdStrmXIDRef(Object value) {
    this.reltdStrmXIDRef = value;
  }

  /**
   * Gets the value of the xidRef property.
   *
   * @return possible object is {@link Object }
   */
  public Object getXIDRef() {
    return xidRef;
  }

  /**
   * Sets the value of the xidRef property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setXIDRef(Object value) {
    this.xidRef = value;
  }
}
