//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * SettlementObligationReport can be found in Volume 5 of the specification
 *
 * <p>Java class for SettlementObligationReport_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SettlementObligationReport_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}SettlementObligationReportElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}SettlementObligationReportAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "SettlementObligationReport_message_t",
  propOrder = {"applSeqCtrl", "settlObligInst"}
)
public class SettlementObligationReportMessageT extends AbstractMessageT {

  @XmlElement(name = "ApplSeqCtrl")
  protected ApplicationSequenceControlBlockT applSeqCtrl;

  @XmlElement(name = "SettlObligInst", required = true)
  protected List<SettlObligationInstructionsBlockT> settlObligInst;

  @XmlAttribute(name = "BizDt")
  protected XMLGregorianCalendar bizDt;

  @XmlAttribute(name = "CycleNo")
  protected BigInteger cycleNo;

  @XmlAttribute(name = "SettlMsgID", required = true)
  protected String settlMsgID;

  @XmlAttribute(name = "SettlMode", required = true)
  protected BigInteger settlMode;

  @XmlAttribute(name = "Txt")
  protected String txt;

  @XmlAttribute(name = "EncTxtLen")
  protected BigInteger encTxtLen;

  @XmlAttribute(name = "EncTxt")
  protected byte[] encTxt;

  @XmlAttribute(name = "TxnTm")
  protected XMLGregorianCalendar txnTm;

  /**
   * Gets the value of the applSeqCtrl property.
   *
   * @return possible object is {@link ApplicationSequenceControlBlockT }
   */
  public ApplicationSequenceControlBlockT getApplSeqCtrl() {
    return applSeqCtrl;
  }

  /**
   * Sets the value of the applSeqCtrl property.
   *
   * @param value allowed object is {@link ApplicationSequenceControlBlockT }
   */
  public void setApplSeqCtrl(ApplicationSequenceControlBlockT value) {
    this.applSeqCtrl = value;
  }

  /**
   * Gets the value of the settlObligInst property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the settlObligInst property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSettlObligInst().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * SettlObligationInstructionsBlockT }
   */
  public List<SettlObligationInstructionsBlockT> getSettlObligInst() {
    if (settlObligInst == null) {
      settlObligInst = new ArrayList<SettlObligationInstructionsBlockT>();
    }
    return this.settlObligInst;
  }

  /**
   * Gets the value of the bizDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getBizDt() {
    return bizDt;
  }

  /**
   * Sets the value of the bizDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setBizDt(XMLGregorianCalendar value) {
    this.bizDt = value;
  }

  /**
   * Gets the value of the cycleNo property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getCycleNo() {
    return cycleNo;
  }

  /**
   * Sets the value of the cycleNo property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setCycleNo(BigInteger value) {
    this.cycleNo = value;
  }

  /**
   * Gets the value of the settlMsgID property.
   *
   * @return possible object is {@link String }
   */
  public String getSettlMsgID() {
    return settlMsgID;
  }

  /**
   * Sets the value of the settlMsgID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSettlMsgID(String value) {
    this.settlMsgID = value;
  }

  /**
   * Gets the value of the settlMode property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getSettlMode() {
    return settlMode;
  }

  /**
   * Sets the value of the settlMode property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setSettlMode(BigInteger value) {
    this.settlMode = value;
  }

  /**
   * Gets the value of the txt property.
   *
   * @return possible object is {@link String }
   */
  public String getTxt() {
    return txt;
  }

  /**
   * Sets the value of the txt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTxt(String value) {
    this.txt = value;
  }

  /**
   * Gets the value of the encTxtLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncTxtLen() {
    return encTxtLen;
  }

  /**
   * Sets the value of the encTxtLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncTxtLen(BigInteger value) {
    this.encTxtLen = value;
  }

  /**
   * Gets the value of the encTxt property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncTxt() {
    return encTxt;
  }

  /**
   * Sets the value of the encTxt property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncTxt(byte[] value) {
    this.encTxt = value;
  }

  /**
   * Gets the value of the txnTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getTxnTm() {
    return txnTm;
  }

  /**
   * Sets the value of the txnTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setTxnTm(XMLGregorianCalendar value) {
    this.txnTm = value;
  }
}
