//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for UnderlyingDividendPayout_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UnderlyingDividendPayout_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UnderlyingDividendPayoutElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UnderlyingDividendPayoutAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "UnderlyingDividendPayout_Block_t",
  propOrder = {"pmt"}
)
public class UnderlyingDividendPayoutBlockT {

  @XmlElement(name = "Pmt")
  protected List<UnderlyingDividendPaymentGrpBlockT> pmt;

  @XmlAttribute(name = "Ratio")
  protected BigDecimal ratio;

  @XmlAttribute(name = "Conds")
  protected String conds;

  /**
   * Gets the value of the pmt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pmt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPmt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingDividendPaymentGrpBlockT }
   */
  public List<UnderlyingDividendPaymentGrpBlockT> getPmt() {
    if (pmt == null) {
      pmt = new ArrayList<UnderlyingDividendPaymentGrpBlockT>();
    }
    return this.pmt;
  }

  /**
   * Gets the value of the ratio property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getRatio() {
    return ratio;
  }

  /**
   * Sets the value of the ratio property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setRatio(BigDecimal value) {
    this.ratio = value;
  }

  /**
   * Gets the value of the conds property.
   *
   * @return possible object is {@link String }
   */
  public String getConds() {
    return conds;
  }

  /**
   * Sets the value of the conds property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConds(String value) {
    this.conds = value;
  }
}
