//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for UnderlyingLegInstrument_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UnderlyingLegInstrument_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UnderlyingLegInstrumentElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UnderlyingLegInstrumentAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "UnderlyingLegInstrument_Block_t",
  propOrder = {"aid"}
)
public class UnderlyingLegInstrumentBlockT {

  @XmlElement(name = "AID")
  protected List<UnderlyingLegSecurityAltIDGrpBlockT> aid;

  @XmlAttribute(name = "Sym")
  protected String sym;

  @XmlAttribute(name = "Sfx")
  protected String sfx;

  @XmlAttribute(name = "ID")
  protected String id;

  @XmlAttribute(name = "Src")
  protected String src;

  @XmlAttribute(name = "CFI")
  protected String cfi;

  @XmlAttribute(name = "SecType")
  protected String secType;

  @XmlAttribute(name = "SubType")
  protected String subType;

  @XmlAttribute(name = "MMY")
  protected String mmy;

  @XmlAttribute(name = "MatDt")
  protected XMLGregorianCalendar matDt;

  @XmlAttribute(name = "MatTm")
  protected XMLGregorianCalendar matTm;

  @XmlAttribute(name = "StrkPx")
  protected BigDecimal strkPx;

  @XmlAttribute(name = "OptAt")
  protected String optAt;

  @XmlAttribute(name = "PutCall")
  protected BigInteger putCall;

  @XmlAttribute(name = "Exch")
  protected String exch;

  @XmlAttribute(name = "Desc")
  protected String desc;

  /**
   * Gets the value of the aid property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the aid property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAID().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingLegSecurityAltIDGrpBlockT }
   */
  public List<UnderlyingLegSecurityAltIDGrpBlockT> getAID() {
    if (aid == null) {
      aid = new ArrayList<UnderlyingLegSecurityAltIDGrpBlockT>();
    }
    return this.aid;
  }

  /**
   * Gets the value of the sym property.
   *
   * @return possible object is {@link String }
   */
  public String getSym() {
    return sym;
  }

  /**
   * Sets the value of the sym property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSym(String value) {
    this.sym = value;
  }

  /**
   * Gets the value of the sfx property.
   *
   * @return possible object is {@link String }
   */
  public String getSfx() {
    return sfx;
  }

  /**
   * Sets the value of the sfx property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSfx(String value) {
    this.sfx = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the src property.
   *
   * @return possible object is {@link String }
   */
  public String getSrc() {
    return src;
  }

  /**
   * Sets the value of the src property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSrc(String value) {
    this.src = value;
  }

  /**
   * Gets the value of the cfi property.
   *
   * @return possible object is {@link String }
   */
  public String getCFI() {
    return cfi;
  }

  /**
   * Sets the value of the cfi property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCFI(String value) {
    this.cfi = value;
  }

  /**
   * Gets the value of the secType property.
   *
   * @return possible object is {@link String }
   */
  public String getSecType() {
    return secType;
  }

  /**
   * Sets the value of the secType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSecType(String value) {
    this.secType = value;
  }

  /**
   * Gets the value of the subType property.
   *
   * @return possible object is {@link String }
   */
  public String getSubType() {
    return subType;
  }

  /**
   * Sets the value of the subType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubType(String value) {
    this.subType = value;
  }

  /**
   * Gets the value of the mmy property.
   *
   * @return possible object is {@link String }
   */
  public String getMMY() {
    return mmy;
  }

  /**
   * Sets the value of the mmy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMMY(String value) {
    this.mmy = value;
  }

  /**
   * Gets the value of the matDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getMatDt() {
    return matDt;
  }

  /**
   * Sets the value of the matDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setMatDt(XMLGregorianCalendar value) {
    this.matDt = value;
  }

  /**
   * Gets the value of the matTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getMatTm() {
    return matTm;
  }

  /**
   * Sets the value of the matTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setMatTm(XMLGregorianCalendar value) {
    this.matTm = value;
  }

  /**
   * Gets the value of the strkPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkPx() {
    return strkPx;
  }

  /**
   * Sets the value of the strkPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkPx(BigDecimal value) {
    this.strkPx = value;
  }

  /**
   * Gets the value of the optAt property.
   *
   * @return possible object is {@link String }
   */
  public String getOptAt() {
    return optAt;
  }

  /**
   * Sets the value of the optAt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOptAt(String value) {
    this.optAt = value;
  }

  /**
   * Gets the value of the putCall property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPutCall() {
    return putCall;
  }

  /**
   * Sets the value of the putCall property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPutCall(BigInteger value) {
    this.putCall = value;
  }

  /**
   * Gets the value of the exch property.
   *
   * @return possible object is {@link String }
   */
  public String getExch() {
    return exch;
  }

  /**
   * Sets the value of the exch property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExch(String value) {
    this.exch = value;
  }

  /**
   * Gets the value of the desc property.
   *
   * @return possible object is {@link String }
   */
  public String getDesc() {
    return desc;
  }

  /**
   * Sets the value of the desc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDesc(String value) {
    this.desc = value;
  }
}
