//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for UndInstrmtGrp_Block_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UndInstrmtGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UndInstrmtGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UndInstrmtGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "UndInstrmtGrp_Block_t",
  propOrder = {
    "undAID",
    "secXML",
    "stip",
    "pty",
    "evnt",
    "scndryAsset",
    "assetAttrb",
    "cmplxEvnt",
    "dtAdjmt",
    "pxngDtTm",
    "mktDsrptn",
    "optExer",
    "strm",
    "prov",
    "addtnlTrm",
    "protctnTrm",
    "cashSettlTrm",
    "physSettlTrm",
    "rtSpreadSched",
    "dividendPay",
    "extrordEvnt"
  }
)
public class UndInstrmtGrpBlockT {

  @XmlElement(name = "UndAID")
  protected List<UndSecAltIDGrpBlockT> undAID;

  @XmlElement(name = "SecXML")
  protected UnderlyingSecurityXMLBlockT secXML;

  @XmlElement(name = "Stip")
  protected List<UnderlyingStipulationsBlockT> stip;

  @XmlElement(name = "Pty")
  protected List<UndlyInstrumentPartiesBlockT> pty;

  @XmlElement(name = "Evnt")
  protected List<UnderlyingEvntGrpBlockT> evnt;

  @XmlElement(name = "ScndryAsset")
  protected List<UnderlyingSecondaryAssetGrpBlockT> scndryAsset;

  @XmlElement(name = "AssetAttrb")
  protected List<UnderlyingAssetAttributeGrpBlockT> assetAttrb;

  @XmlElement(name = "CmplxEvnt")
  protected List<UnderlyingComplexEventsBlockT> cmplxEvnt;

  @XmlElement(name = "DtAdjmt")
  protected UnderlyingDateAdjustmentBlockT dtAdjmt;

  @XmlElement(name = "PxngDtTm")
  protected UnderlyingPricingDateTimeBlockT pxngDtTm;

  @XmlElement(name = "MktDsrptn")
  protected UnderlyingMarketDisruptionBlockT mktDsrptn;

  @XmlElement(name = "OptExer")
  protected UnderlyingOptionExerciseBlockT optExer;

  @XmlElement(name = "Strm")
  protected List<UnderlyingStreamGrpBlockT> strm;

  @XmlElement(name = "Prov")
  protected List<UnderlyingProvisionGrpBlockT> prov;

  @XmlElement(name = "AddtnlTrm")
  protected List<UnderlyingAdditionalTermGrpBlockT> addtnlTrm;

  @XmlElement(name = "ProtctnTrm")
  protected List<UnderlyingProtectionTermGrpBlockT> protctnTrm;

  @XmlElement(name = "CashSettlTrm")
  protected List<UnderlyingCashSettlTermGrpBlockT> cashSettlTrm;

  @XmlElement(name = "PhysSettlTrm")
  protected List<UnderlyingPhysicalSettlTermGrpBlockT> physSettlTrm;

  @XmlElement(name = "RtSpreadSched")
  protected UnderlyingRateSpreadScheduleBlockT rtSpreadSched;

  @XmlElement(name = "DividendPay")
  protected UnderlyingDividendPayoutBlockT dividendPay;

  @XmlElement(name = "ExtrordEvnt")
  protected List<UnderlyingExtraordinaryEventGrpBlockT> extrordEvnt;

  @XmlAttribute(name = "Sym")
  protected String sym;

  @XmlAttribute(name = "Sfx")
  protected SymbolSfxEnumT sfx;

  @XmlAttribute(name = "ID")
  protected String id;

  @XmlAttribute(name = "Src")
  protected String src;

  @XmlAttribute(name = "Prod")
  protected BigInteger prod;

  @XmlAttribute(name = "CFI")
  protected String cfi;

  @XmlAttribute(name = "SecTyp")
  protected String secTyp;

  @XmlAttribute(name = "SubTyp")
  protected String subTyp;

  @XmlAttribute(name = "MMY")
  protected String mmy;

  @XmlAttribute(name = "Mat")
  protected XMLGregorianCalendar mat;

  @XmlAttribute(name = "MatTm")
  protected XMLGregorianCalendar matTm;

  @XmlAttribute(name = "PxRefMo")
  protected String pxRefMo;

  @XmlAttribute(name = "CpnPmt")
  protected XMLGregorianCalendar cpnPmt;

  @XmlAttribute(name = "RestrctTyp")
  protected RestructuringTypeEnumT restrctTyp;

  @XmlAttribute(name = "Snrty")
  protected SeniorityEnumT snrty;

  @XmlAttribute(name = "Notl")
  protected BigDecimal notl;

  @XmlAttribute(name = "NotlCcy")
  protected String notlCcy;

  @XmlAttribute(name = "NotlDtrmnMeth")
  protected String notlDtrmnMeth;

  @XmlAttribute(name = "NotlAdjmts")
  protected BigInteger notlAdjmts;

  @XmlAttribute(name = "NotlXIDRef")
  @XmlIDREF
  protected Object notlXIDRef;

  @XmlAttribute(name = "NotlPctOut")
  protected BigDecimal notlPctOut;

  @XmlAttribute(name = "OrigNotlPctOut")
  protected BigDecimal origNotlPctOut;

  @XmlAttribute(name = "AttchPnt")
  protected BigDecimal attchPnt;

  @XmlAttribute(name = "DetchPnt")
  protected BigDecimal detchPnt;

  @XmlAttribute(name = "Issued")
  protected XMLGregorianCalendar issued;

  @XmlAttribute(name = "RepoCollSecTyp")
  protected String repoCollSecTyp;

  @XmlAttribute(name = "RepoTrm")
  protected BigInteger repoTrm;

  @XmlAttribute(name = "RepoRt")
  protected BigDecimal repoRt;

  @XmlAttribute(name = "Fctr")
  protected BigDecimal fctr;

  @XmlAttribute(name = "CrdRtg")
  protected String crdRtg;

  @XmlAttribute(name = "Rgstry")
  protected String rgstry;

  @XmlAttribute(name = "Ctry")
  protected String ctry;

  @XmlAttribute(name = "StOrProvnc")
  protected String stOrProvnc;

  @XmlAttribute(name = "Lcl")
  protected String lcl;

  @XmlAttribute(name = "Redeem")
  protected XMLGregorianCalendar redeem;

  @XmlAttribute(name = "StrkPx")
  protected BigDecimal strkPx;

  @XmlAttribute(name = "StrkCcy")
  protected String strkCcy;

  @XmlAttribute(name = "OptA")
  protected String optA;

  @XmlAttribute(name = "Mult")
  protected BigDecimal mult;

  @XmlAttribute(name = "MultTyp")
  protected BigInteger multTyp;

  @XmlAttribute(name = "TrdgUnitPeriodMult")
  protected BigInteger trdgUnitPeriodMult;

  @XmlAttribute(name = "FlowSchedTyp")
  protected String flowSchedTyp;

  @XmlAttribute(name = "UOM")
  protected UnitOfMeasureEnumT uom;

  @XmlAttribute(name = "UOMQty")
  protected BigDecimal uomQty;

  @XmlAttribute(name = "UOMCcy")
  protected String uomCcy;

  @XmlAttribute(name = "PxUOM")
  protected UnitOfMeasureEnumT pxUOM;

  @XmlAttribute(name = "PxUOMQty")
  protected BigDecimal pxUOMQty;

  @XmlAttribute(name = "PxUOMCcy")
  protected String pxUOMCcy;

  @XmlAttribute(name = "TmUnit")
  protected TimeUnitEnumT tmUnit;

  @XmlAttribute(name = "ExerStyle")
  protected BigInteger exerStyle;

  @XmlAttribute(name = "PxQteCcy")
  protected String pxQteCcy;

  @XmlAttribute(name = "CpnRt")
  protected BigDecimal cpnRt;

  @XmlAttribute(name = "Exch")
  protected String exch;

  @XmlAttribute(name = "Issr")
  protected String issr;

  @XmlAttribute(name = "EncUndIssrLen")
  protected BigInteger encUndIssrLen;

  @XmlAttribute(name = "EncUndIssr")
  protected byte[] encUndIssr;

  @XmlAttribute(name = "ShrtName")
  protected String shrtName;

  @XmlAttribute(name = "FullName")
  protected String fullName;

  @XmlAttribute(name = "EncFullNameLen")
  protected BigInteger encFullNameLen;

  @XmlAttribute(name = "EncFullName")
  protected byte[] encFullName;

  @XmlAttribute(name = "NdxUnit")
  protected PaymentStreamRateIndexCurveUnitEnumT ndxUnit;

  @XmlAttribute(name = "NdxPeriod")
  protected BigInteger ndxPeriod;

  @XmlAttribute(name = "Desc")
  protected String desc;

  @XmlAttribute(name = "EncUndSecDescLen")
  protected BigInteger encUndSecDescLen;

  @XmlAttribute(name = "EncUndSecDesc")
  protected byte[] encUndSecDesc;

  @XmlAttribute(name = "CPPgm")
  protected String cpPgm;

  @XmlAttribute(name = "CPRegTyp")
  protected String cpRegTyp;

  @XmlAttribute(name = "AllocPct")
  protected BigDecimal allocPct;

  @XmlAttribute(name = "Ccy")
  protected String ccy;

  @XmlAttribute(name = "Qty")
  protected BigDecimal qty;

  @XmlAttribute(name = "SettlTyp")
  protected BigInteger settlTyp;

  @XmlAttribute(name = "CashAmt")
  protected BigDecimal cashAmt;

  @XmlAttribute(name = "CashTyp")
  protected UnderlyingCashTypeEnumT cashTyp;

  @XmlAttribute(name = "Px")
  protected BigDecimal px;

  @XmlAttribute(name = "DirtPx")
  protected BigDecimal dirtPx;

  @XmlAttribute(name = "EndPx")
  protected BigDecimal endPx;

  @XmlAttribute(name = "StartVal")
  protected BigDecimal startVal;

  @XmlAttribute(name = "CurVal")
  protected BigDecimal curVal;

  @XmlAttribute(name = "EndVal")
  protected BigDecimal endVal;

  @XmlAttribute(name = "AdjQty")
  protected BigDecimal adjQty;

  @XmlAttribute(name = "FxRate")
  protected BigDecimal fxRate;

  @XmlAttribute(name = "FxRateCalc")
  protected UnderlyingFXRateCalcEnumT fxRateCalc;

  @XmlAttribute(name = "CapValu")
  protected BigDecimal capValu;

  @XmlAttribute(name = "SetMeth")
  protected SettlMethodEnumT setMeth;

  @XmlAttribute(name = "PutCall")
  protected BigInteger putCall;

  @XmlAttribute(name = "ITMCond")
  protected BigInteger itmCond;

  @XmlAttribute(name = "CntraryInstEligInd")
  protected String cntraryInstEligInd;

  @XmlAttribute(name = "ConstuentWt")
  protected BigDecimal constuentWt;

  @XmlAttribute(name = "CpnTyp")
  protected BigInteger cpnTyp;

  @XmlAttribute(name = "TotIssuedAmt")
  protected BigDecimal totIssuedAmt;

  @XmlAttribute(name = "CpnPeriod")
  protected BigInteger cpnPeriod;

  @XmlAttribute(name = "CpnUnit")
  protected CouponFrequencyUnitEnumT cpnUnit;

  @XmlAttribute(name = "CpnDayCnt")
  protected String cpnDayCnt;

  @XmlAttribute(name = "ObligID")
  protected String obligID;

  @XmlAttribute(name = "ObligIDSrc")
  protected String obligIDSrc;

  @XmlAttribute(name = "EqtyID")
  protected String eqtyID;

  @XmlAttribute(name = "EqtyIDSrc")
  protected String eqtyIDSrc;

  @XmlAttribute(name = "FutID")
  protected String futID;

  @XmlAttribute(name = "FutIDSrc")
  protected String futIDSrc;

  @XmlAttribute(name = "LienSnrty")
  protected BigInteger lienSnrty;

  @XmlAttribute(name = "LoanFclty")
  protected BigInteger loanFclty;

  @XmlAttribute(name = "RefEntityTyp")
  protected BigInteger refEntityTyp;

  @XmlAttribute(name = "NdxSeries")
  protected BigInteger ndxSeries;

  @XmlAttribute(name = "NdxAnxVer")
  protected BigInteger ndxAnxVer;

  @XmlAttribute(name = "NdxAnxDt")
  protected XMLGregorianCalendar ndxAnxDt;

  @XmlAttribute(name = "NdxAnxSrc")
  protected String ndxAnxSrc;

  @XmlAttribute(name = "SettlNdx")
  protected String settlNdx;

  @XmlAttribute(name = "SettlNdxLctn")
  protected String settlNdxLctn;

  @XmlAttribute(name = "ExpDesc")
  protected String expDesc;

  @XmlAttribute(name = "EncExpDescLen")
  protected BigInteger encExpDescLen;

  @XmlAttribute(name = "EncExpDesc")
  protected byte[] encExpDesc;

  @XmlAttribute(name = "ProdCmplx")
  protected String prodCmplx;

  @XmlAttribute(name = "SecGrp")
  protected String secGrp;

  @XmlAttribute(name = "SettlOnOpenFlag")
  protected String settlOnOpenFlag;

  @XmlAttribute(name = "AsgnMeth")
  protected InstrmtAssignmentMethodEnumT asgnMeth;

  @XmlAttribute(name = "Status")
  protected String status;

  @XmlAttribute(name = "ObligTyp")
  protected String obligTyp;

  @XmlAttribute(name = "AssetGrp")
  protected BigInteger assetGrp;

  @XmlAttribute(name = "AssetClss")
  protected BigInteger assetClss;

  @XmlAttribute(name = "AssetSubClss")
  protected String assetSubClss;

  @XmlAttribute(name = "AssetTyp")
  protected String assetTyp;

  @XmlAttribute(name = "AsstSubTyp")
  protected String asstSubTyp;

  @XmlAttribute(name = "SwapClss")
  protected SwapClassEnumT swapClss;

  @XmlAttribute(name = "SwapSubClss")
  protected SwapSubClassEnumT swapSubClss;

  @XmlAttribute(name = "NthDflt")
  protected BigInteger nthDflt;

  @XmlAttribute(name = "MthDflt")
  protected BigInteger mthDflt;

  @XmlAttribute(name = "SettldMtrxSrc")
  protected String settldMtrxSrc;

  @XmlAttribute(name = "SettldMtrxDt")
  protected XMLGregorianCalendar settldMtrxDt;

  @XmlAttribute(name = "StrkMult")
  protected BigDecimal strkMult;

  @XmlAttribute(name = "StrkValu")
  protected BigDecimal strkValu;

  @XmlAttribute(name = "StrkUOM")
  protected UnitOfMeasureEnumT strkUOM;

  @XmlAttribute(name = "StrkNdxPnt")
  protected String strkNdxPnt;

  @XmlAttribute(name = "StrkNdx")
  protected String strkNdx;

  @XmlAttribute(name = "StrkNdxQte")
  protected BigInteger strkNdxQte;

  @XmlAttribute(name = "StrkSpread")
  protected BigDecimal strkSpread;

  @XmlAttribute(name = "StrkPxDtrmnMeth")
  protected BigInteger strkPxDtrmnMeth;

  @XmlAttribute(name = "StrkPxBndryMeth")
  protected BigInteger strkPxBndryMeth;

  @XmlAttribute(name = "StrkPxBndryPrcsn")
  protected BigDecimal strkPxBndryPrcsn;

  @XmlAttribute(name = "MinPxIncr")
  protected BigDecimal minPxIncr;

  @XmlAttribute(name = "MinPxIncrAmt")
  protected BigDecimal minPxIncrAmt;

  @XmlAttribute(name = "OptPayoutTyp")
  protected BigInteger optPayoutTyp;

  @XmlAttribute(name = "OptPayAmt")
  protected BigDecimal optPayAmt;

  @XmlAttribute(name = "RtnTrgr")
  protected BigInteger rtnTrgr;

  @XmlAttribute(name = "PxQteMeth")
  protected PriceQuoteMethodEnumT pxQteMeth;

  @XmlAttribute(name = "ValMeth")
  protected ValuationMethodEnumT valMeth;

  @XmlAttribute(name = "ValSrc")
  protected String valSrc;

  @XmlAttribute(name = "ValRefModel")
  protected String valRefModel;

  @XmlAttribute(name = "ListMeth")
  protected BigInteger listMeth;

  @XmlAttribute(name = "CapPx")
  protected BigDecimal capPx;

  @XmlAttribute(name = "FlrPx")
  protected BigDecimal flrPx;

  @XmlAttribute(name = "FlexInd")
  protected String flexInd;

  @XmlAttribute(name = "FlexProdElig")
  protected String flexProdElig;

  @XmlAttribute(name = "PosLmt")
  protected BigInteger posLmt;

  @XmlAttribute(name = "NTPosLmt")
  protected BigInteger ntPosLmt;

  @XmlAttribute(name = "Pool")
  protected String pool;

  @XmlAttribute(name = "CSetMo")
  protected String cSetMo;

  @XmlAttribute(name = "Dated")
  protected XMLGregorianCalendar dated;

  @XmlAttribute(name = "IntAcrl")
  protected XMLGregorianCalendar intAcrl;

  @XmlAttribute(name = "ShrtRstctn")
  protected BigInteger shrtRstctn;

  @XmlAttribute(name = "RefTickTblID")
  protected BigInteger refTickTblID;

  @XmlAttribute(name = "ProtctnXIDRef")
  @XmlIDREF
  protected Object protctnXIDRef;

  @XmlAttribute(name = "SettlXIDRef")
  @XmlIDREF
  protected Object settlXIDRef;

  @XmlAttribute(name = "StrtTyp")
  protected StrategyTypeEnumT strtTyp;

  @XmlAttribute(name = "CmnPxng")
  protected String cmnPxng;

  @XmlAttribute(name = "SettlDsrptnProv")
  protected BigInteger settlDsrptnProv;

  @XmlAttribute(name = "RteChrtr")
  protected String rteChrtr;

  @XmlAttribute(name = "RndDirctn")
  protected String rndDirctn;

  @XmlAttribute(name = "RndPrcsn")
  protected BigInteger rndPrcsn;

  @XmlAttribute(name = "ExtrordEvntAdjMeth")
  protected BigInteger extrordEvntAdjMeth;

  @XmlAttribute(name = "ExchLookAlike")
  protected String exchLookAlike;

  @XmlAttribute(name = "AvgLmtPctg")
  protected BigDecimal avgLmtPctg;

  @XmlAttribute(name = "AvgLmtDys")
  protected BigInteger avgLmtDys;

  @XmlAttribute(name = "DpstryRcptInd")
  protected String dpstryRcptInd;

  @XmlAttribute(name = "OpnUnits")
  protected BigDecimal opnUnits;

  @XmlAttribute(name = "BsktDvsr")
  protected BigDecimal bsktDvsr;

  @XmlAttribute(name = "XID")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  protected String xid;

  /**
   * Gets the value of the undAID property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the undAID property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getUndAID().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UndSecAltIDGrpBlockT }
   */
  public List<UndSecAltIDGrpBlockT> getUndAID() {
    if (undAID == null) {
      undAID = new ArrayList<UndSecAltIDGrpBlockT>();
    }
    return this.undAID;
  }

  /**
   * Gets the value of the secXML property.
   *
   * @return possible object is {@link UnderlyingSecurityXMLBlockT }
   */
  public UnderlyingSecurityXMLBlockT getSecXML() {
    return secXML;
  }

  /**
   * Sets the value of the secXML property.
   *
   * @param value allowed object is {@link UnderlyingSecurityXMLBlockT }
   */
  public void setSecXML(UnderlyingSecurityXMLBlockT value) {
    this.secXML = value;
  }

  /**
   * Gets the value of the stip property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the stip property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getStip().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UnderlyingStipulationsBlockT
   * }
   */
  public List<UnderlyingStipulationsBlockT> getStip() {
    if (stip == null) {
      stip = new ArrayList<UnderlyingStipulationsBlockT>();
    }
    return this.stip;
  }

  /**
   * Gets the value of the pty property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the pty property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPty().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UndlyInstrumentPartiesBlockT
   * }
   */
  public List<UndlyInstrumentPartiesBlockT> getPty() {
    if (pty == null) {
      pty = new ArrayList<UndlyInstrumentPartiesBlockT>();
    }
    return this.pty;
  }

  /**
   * Gets the value of the evnt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the evnt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getEvnt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UnderlyingEvntGrpBlockT }
   */
  public List<UnderlyingEvntGrpBlockT> getEvnt() {
    if (evnt == null) {
      evnt = new ArrayList<UnderlyingEvntGrpBlockT>();
    }
    return this.evnt;
  }

  /**
   * Gets the value of the scndryAsset property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the scndryAsset property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getScndryAsset().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingSecondaryAssetGrpBlockT }
   */
  public List<UnderlyingSecondaryAssetGrpBlockT> getScndryAsset() {
    if (scndryAsset == null) {
      scndryAsset = new ArrayList<UnderlyingSecondaryAssetGrpBlockT>();
    }
    return this.scndryAsset;
  }

  /**
   * Gets the value of the assetAttrb property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the assetAttrb property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAssetAttrb().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingAssetAttributeGrpBlockT }
   */
  public List<UnderlyingAssetAttributeGrpBlockT> getAssetAttrb() {
    if (assetAttrb == null) {
      assetAttrb = new ArrayList<UnderlyingAssetAttributeGrpBlockT>();
    }
    return this.assetAttrb;
  }

  /**
   * Gets the value of the cmplxEvnt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the cmplxEvnt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCmplxEvnt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingComplexEventsBlockT }
   */
  public List<UnderlyingComplexEventsBlockT> getCmplxEvnt() {
    if (cmplxEvnt == null) {
      cmplxEvnt = new ArrayList<UnderlyingComplexEventsBlockT>();
    }
    return this.cmplxEvnt;
  }

  /**
   * Gets the value of the dtAdjmt property.
   *
   * @return possible object is {@link UnderlyingDateAdjustmentBlockT }
   */
  public UnderlyingDateAdjustmentBlockT getDtAdjmt() {
    return dtAdjmt;
  }

  /**
   * Sets the value of the dtAdjmt property.
   *
   * @param value allowed object is {@link UnderlyingDateAdjustmentBlockT }
   */
  public void setDtAdjmt(UnderlyingDateAdjustmentBlockT value) {
    this.dtAdjmt = value;
  }

  /**
   * Gets the value of the pxngDtTm property.
   *
   * @return possible object is {@link UnderlyingPricingDateTimeBlockT }
   */
  public UnderlyingPricingDateTimeBlockT getPxngDtTm() {
    return pxngDtTm;
  }

  /**
   * Sets the value of the pxngDtTm property.
   *
   * @param value allowed object is {@link UnderlyingPricingDateTimeBlockT }
   */
  public void setPxngDtTm(UnderlyingPricingDateTimeBlockT value) {
    this.pxngDtTm = value;
  }

  /**
   * Gets the value of the mktDsrptn property.
   *
   * @return possible object is {@link UnderlyingMarketDisruptionBlockT }
   */
  public UnderlyingMarketDisruptionBlockT getMktDsrptn() {
    return mktDsrptn;
  }

  /**
   * Sets the value of the mktDsrptn property.
   *
   * @param value allowed object is {@link UnderlyingMarketDisruptionBlockT }
   */
  public void setMktDsrptn(UnderlyingMarketDisruptionBlockT value) {
    this.mktDsrptn = value;
  }

  /**
   * Gets the value of the optExer property.
   *
   * @return possible object is {@link UnderlyingOptionExerciseBlockT }
   */
  public UnderlyingOptionExerciseBlockT getOptExer() {
    return optExer;
  }

  /**
   * Sets the value of the optExer property.
   *
   * @param value allowed object is {@link UnderlyingOptionExerciseBlockT }
   */
  public void setOptExer(UnderlyingOptionExerciseBlockT value) {
    this.optExer = value;
  }

  /**
   * Gets the value of the strm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the strm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getStrm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UnderlyingStreamGrpBlockT }
   */
  public List<UnderlyingStreamGrpBlockT> getStrm() {
    if (strm == null) {
      strm = new ArrayList<UnderlyingStreamGrpBlockT>();
    }
    return this.strm;
  }

  /**
   * Gets the value of the prov property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the prov property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getProv().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link UnderlyingProvisionGrpBlockT
   * }
   */
  public List<UnderlyingProvisionGrpBlockT> getProv() {
    if (prov == null) {
      prov = new ArrayList<UnderlyingProvisionGrpBlockT>();
    }
    return this.prov;
  }

  /**
   * Gets the value of the addtnlTrm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the addtnlTrm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAddtnlTrm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingAdditionalTermGrpBlockT }
   */
  public List<UnderlyingAdditionalTermGrpBlockT> getAddtnlTrm() {
    if (addtnlTrm == null) {
      addtnlTrm = new ArrayList<UnderlyingAdditionalTermGrpBlockT>();
    }
    return this.addtnlTrm;
  }

  /**
   * Gets the value of the protctnTrm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the protctnTrm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getProtctnTrm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingProtectionTermGrpBlockT }
   */
  public List<UnderlyingProtectionTermGrpBlockT> getProtctnTrm() {
    if (protctnTrm == null) {
      protctnTrm = new ArrayList<UnderlyingProtectionTermGrpBlockT>();
    }
    return this.protctnTrm;
  }

  /**
   * Gets the value of the cashSettlTrm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the cashSettlTrm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCashSettlTrm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingCashSettlTermGrpBlockT }
   */
  public List<UnderlyingCashSettlTermGrpBlockT> getCashSettlTrm() {
    if (cashSettlTrm == null) {
      cashSettlTrm = new ArrayList<UnderlyingCashSettlTermGrpBlockT>();
    }
    return this.cashSettlTrm;
  }

  /**
   * Gets the value of the physSettlTrm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the physSettlTrm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getPhysSettlTrm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingPhysicalSettlTermGrpBlockT }
   */
  public List<UnderlyingPhysicalSettlTermGrpBlockT> getPhysSettlTrm() {
    if (physSettlTrm == null) {
      physSettlTrm = new ArrayList<UnderlyingPhysicalSettlTermGrpBlockT>();
    }
    return this.physSettlTrm;
  }

  /**
   * Gets the value of the rtSpreadSched property.
   *
   * @return possible object is {@link UnderlyingRateSpreadScheduleBlockT }
   */
  public UnderlyingRateSpreadScheduleBlockT getRtSpreadSched() {
    return rtSpreadSched;
  }

  /**
   * Sets the value of the rtSpreadSched property.
   *
   * @param value allowed object is {@link UnderlyingRateSpreadScheduleBlockT }
   */
  public void setRtSpreadSched(UnderlyingRateSpreadScheduleBlockT value) {
    this.rtSpreadSched = value;
  }

  /**
   * Gets the value of the dividendPay property.
   *
   * @return possible object is {@link UnderlyingDividendPayoutBlockT }
   */
  public UnderlyingDividendPayoutBlockT getDividendPay() {
    return dividendPay;
  }

  /**
   * Sets the value of the dividendPay property.
   *
   * @param value allowed object is {@link UnderlyingDividendPayoutBlockT }
   */
  public void setDividendPay(UnderlyingDividendPayoutBlockT value) {
    this.dividendPay = value;
  }

  /**
   * Gets the value of the extrordEvnt property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extrordEvnt property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtrordEvnt().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * UnderlyingExtraordinaryEventGrpBlockT }
   */
  public List<UnderlyingExtraordinaryEventGrpBlockT> getExtrordEvnt() {
    if (extrordEvnt == null) {
      extrordEvnt = new ArrayList<UnderlyingExtraordinaryEventGrpBlockT>();
    }
    return this.extrordEvnt;
  }

  /**
   * Gets the value of the sym property.
   *
   * @return possible object is {@link String }
   */
  public String getSym() {
    return sym;
  }

  /**
   * Sets the value of the sym property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSym(String value) {
    this.sym = value;
  }

  /**
   * Gets the value of the sfx property.
   *
   * @return possible object is {@link SymbolSfxEnumT }
   */
  public SymbolSfxEnumT getSfx() {
    return sfx;
  }

  /**
   * Sets the value of the sfx property.
   *
   * @param value allowed object is {@link SymbolSfxEnumT }
   */
  public void setSfx(SymbolSfxEnumT value) {
    this.sfx = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the src property.
   *
   * @return possible object is {@link String }
   */
  public String getSrc() {
    return src;
  }

  /**
   * Sets the value of the src property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSrc(String value) {
    this.src = value;
  }

  /**
   * Gets the value of the prod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getProd() {
    return prod;
  }

  /**
   * Sets the value of the prod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setProd(BigInteger value) {
    this.prod = value;
  }

  /**
   * Gets the value of the cfi property.
   *
   * @return possible object is {@link String }
   */
  public String getCFI() {
    return cfi;
  }

  /**
   * Sets the value of the cfi property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCFI(String value) {
    this.cfi = value;
  }

  /**
   * Gets the value of the secTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getSecTyp() {
    return secTyp;
  }

  /**
   * Sets the value of the secTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSecTyp(String value) {
    this.secTyp = value;
  }

  /**
   * Gets the value of the subTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getSubTyp() {
    return subTyp;
  }

  /**
   * Sets the value of the subTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubTyp(String value) {
    this.subTyp = value;
  }

  /**
   * Gets the value of the mmy property.
   *
   * @return possible object is {@link String }
   */
  public String getMMY() {
    return mmy;
  }

  /**
   * Sets the value of the mmy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMMY(String value) {
    this.mmy = value;
  }

  /**
   * Gets the value of the mat property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getMat() {
    return mat;
  }

  /**
   * Sets the value of the mat property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setMat(XMLGregorianCalendar value) {
    this.mat = value;
  }

  /**
   * Gets the value of the matTm property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getMatTm() {
    return matTm;
  }

  /**
   * Sets the value of the matTm property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setMatTm(XMLGregorianCalendar value) {
    this.matTm = value;
  }

  /**
   * Gets the value of the pxRefMo property.
   *
   * @return possible object is {@link String }
   */
  public String getPxRefMo() {
    return pxRefMo;
  }

  /**
   * Sets the value of the pxRefMo property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPxRefMo(String value) {
    this.pxRefMo = value;
  }

  /**
   * Gets the value of the cpnPmt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getCpnPmt() {
    return cpnPmt;
  }

  /**
   * Sets the value of the cpnPmt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setCpnPmt(XMLGregorianCalendar value) {
    this.cpnPmt = value;
  }

  /**
   * Gets the value of the restrctTyp property.
   *
   * @return possible object is {@link RestructuringTypeEnumT }
   */
  public RestructuringTypeEnumT getRestrctTyp() {
    return restrctTyp;
  }

  /**
   * Sets the value of the restrctTyp property.
   *
   * @param value allowed object is {@link RestructuringTypeEnumT }
   */
  public void setRestrctTyp(RestructuringTypeEnumT value) {
    this.restrctTyp = value;
  }

  /**
   * Gets the value of the snrty property.
   *
   * @return possible object is {@link SeniorityEnumT }
   */
  public SeniorityEnumT getSnrty() {
    return snrty;
  }

  /**
   * Sets the value of the snrty property.
   *
   * @param value allowed object is {@link SeniorityEnumT }
   */
  public void setSnrty(SeniorityEnumT value) {
    this.snrty = value;
  }

  /**
   * Gets the value of the notl property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getNotl() {
    return notl;
  }

  /**
   * Sets the value of the notl property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setNotl(BigDecimal value) {
    this.notl = value;
  }

  /**
   * Gets the value of the notlCcy property.
   *
   * @return possible object is {@link String }
   */
  public String getNotlCcy() {
    return notlCcy;
  }

  /**
   * Sets the value of the notlCcy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNotlCcy(String value) {
    this.notlCcy = value;
  }

  /**
   * Gets the value of the notlDtrmnMeth property.
   *
   * @return possible object is {@link String }
   */
  public String getNotlDtrmnMeth() {
    return notlDtrmnMeth;
  }

  /**
   * Sets the value of the notlDtrmnMeth property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNotlDtrmnMeth(String value) {
    this.notlDtrmnMeth = value;
  }

  /**
   * Gets the value of the notlAdjmts property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNotlAdjmts() {
    return notlAdjmts;
  }

  /**
   * Sets the value of the notlAdjmts property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNotlAdjmts(BigInteger value) {
    this.notlAdjmts = value;
  }

  /**
   * Gets the value of the notlXIDRef property.
   *
   * @return possible object is {@link Object }
   */
  public Object getNotlXIDRef() {
    return notlXIDRef;
  }

  /**
   * Sets the value of the notlXIDRef property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setNotlXIDRef(Object value) {
    this.notlXIDRef = value;
  }

  /**
   * Gets the value of the notlPctOut property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getNotlPctOut() {
    return notlPctOut;
  }

  /**
   * Sets the value of the notlPctOut property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setNotlPctOut(BigDecimal value) {
    this.notlPctOut = value;
  }

  /**
   * Gets the value of the origNotlPctOut property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getOrigNotlPctOut() {
    return origNotlPctOut;
  }

  /**
   * Sets the value of the origNotlPctOut property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setOrigNotlPctOut(BigDecimal value) {
    this.origNotlPctOut = value;
  }

  /**
   * Gets the value of the attchPnt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getAttchPnt() {
    return attchPnt;
  }

  /**
   * Sets the value of the attchPnt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setAttchPnt(BigDecimal value) {
    this.attchPnt = value;
  }

  /**
   * Gets the value of the detchPnt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getDetchPnt() {
    return detchPnt;
  }

  /**
   * Sets the value of the detchPnt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setDetchPnt(BigDecimal value) {
    this.detchPnt = value;
  }

  /**
   * Gets the value of the issued property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getIssued() {
    return issued;
  }

  /**
   * Sets the value of the issued property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setIssued(XMLGregorianCalendar value) {
    this.issued = value;
  }

  /**
   * Gets the value of the repoCollSecTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getRepoCollSecTyp() {
    return repoCollSecTyp;
  }

  /**
   * Sets the value of the repoCollSecTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRepoCollSecTyp(String value) {
    this.repoCollSecTyp = value;
  }

  /**
   * Gets the value of the repoTrm property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRepoTrm() {
    return repoTrm;
  }

  /**
   * Sets the value of the repoTrm property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRepoTrm(BigInteger value) {
    this.repoTrm = value;
  }

  /**
   * Gets the value of the repoRt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getRepoRt() {
    return repoRt;
  }

  /**
   * Sets the value of the repoRt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setRepoRt(BigDecimal value) {
    this.repoRt = value;
  }

  /**
   * Gets the value of the fctr property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getFctr() {
    return fctr;
  }

  /**
   * Sets the value of the fctr property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setFctr(BigDecimal value) {
    this.fctr = value;
  }

  /**
   * Gets the value of the crdRtg property.
   *
   * @return possible object is {@link String }
   */
  public String getCrdRtg() {
    return crdRtg;
  }

  /**
   * Sets the value of the crdRtg property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCrdRtg(String value) {
    this.crdRtg = value;
  }

  /**
   * Gets the value of the rgstry property.
   *
   * @return possible object is {@link String }
   */
  public String getRgstry() {
    return rgstry;
  }

  /**
   * Sets the value of the rgstry property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRgstry(String value) {
    this.rgstry = value;
  }

  /**
   * Gets the value of the ctry property.
   *
   * @return possible object is {@link String }
   */
  public String getCtry() {
    return ctry;
  }

  /**
   * Sets the value of the ctry property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCtry(String value) {
    this.ctry = value;
  }

  /**
   * Gets the value of the stOrProvnc property.
   *
   * @return possible object is {@link String }
   */
  public String getStOrProvnc() {
    return stOrProvnc;
  }

  /**
   * Sets the value of the stOrProvnc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStOrProvnc(String value) {
    this.stOrProvnc = value;
  }

  /**
   * Gets the value of the lcl property.
   *
   * @return possible object is {@link String }
   */
  public String getLcl() {
    return lcl;
  }

  /**
   * Sets the value of the lcl property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLcl(String value) {
    this.lcl = value;
  }

  /**
   * Gets the value of the redeem property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getRedeem() {
    return redeem;
  }

  /**
   * Sets the value of the redeem property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setRedeem(XMLGregorianCalendar value) {
    this.redeem = value;
  }

  /**
   * Gets the value of the strkPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkPx() {
    return strkPx;
  }

  /**
   * Sets the value of the strkPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkPx(BigDecimal value) {
    this.strkPx = value;
  }

  /**
   * Gets the value of the strkCcy property.
   *
   * @return possible object is {@link String }
   */
  public String getStrkCcy() {
    return strkCcy;
  }

  /**
   * Sets the value of the strkCcy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStrkCcy(String value) {
    this.strkCcy = value;
  }

  /**
   * Gets the value of the optA property.
   *
   * @return possible object is {@link String }
   */
  public String getOptA() {
    return optA;
  }

  /**
   * Sets the value of the optA property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOptA(String value) {
    this.optA = value;
  }

  /**
   * Gets the value of the mult property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getMult() {
    return mult;
  }

  /**
   * Sets the value of the mult property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setMult(BigDecimal value) {
    this.mult = value;
  }

  /**
   * Gets the value of the multTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMultTyp() {
    return multTyp;
  }

  /**
   * Sets the value of the multTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMultTyp(BigInteger value) {
    this.multTyp = value;
  }

  /**
   * Gets the value of the trdgUnitPeriodMult property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getTrdgUnitPeriodMult() {
    return trdgUnitPeriodMult;
  }

  /**
   * Sets the value of the trdgUnitPeriodMult property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setTrdgUnitPeriodMult(BigInteger value) {
    this.trdgUnitPeriodMult = value;
  }

  /**
   * Gets the value of the flowSchedTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getFlowSchedTyp() {
    return flowSchedTyp;
  }

  /**
   * Sets the value of the flowSchedTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFlowSchedTyp(String value) {
    this.flowSchedTyp = value;
  }

  /**
   * Gets the value of the uom property.
   *
   * @return possible object is {@link UnitOfMeasureEnumT }
   */
  public UnitOfMeasureEnumT getUOM() {
    return uom;
  }

  /**
   * Sets the value of the uom property.
   *
   * @param value allowed object is {@link UnitOfMeasureEnumT }
   */
  public void setUOM(UnitOfMeasureEnumT value) {
    this.uom = value;
  }

  /**
   * Gets the value of the uomQty property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getUOMQty() {
    return uomQty;
  }

  /**
   * Sets the value of the uomQty property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setUOMQty(BigDecimal value) {
    this.uomQty = value;
  }

  /**
   * Gets the value of the uomCcy property.
   *
   * @return possible object is {@link String }
   */
  public String getUOMCcy() {
    return uomCcy;
  }

  /**
   * Sets the value of the uomCcy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUOMCcy(String value) {
    this.uomCcy = value;
  }

  /**
   * Gets the value of the pxUOM property.
   *
   * @return possible object is {@link UnitOfMeasureEnumT }
   */
  public UnitOfMeasureEnumT getPxUOM() {
    return pxUOM;
  }

  /**
   * Sets the value of the pxUOM property.
   *
   * @param value allowed object is {@link UnitOfMeasureEnumT }
   */
  public void setPxUOM(UnitOfMeasureEnumT value) {
    this.pxUOM = value;
  }

  /**
   * Gets the value of the pxUOMQty property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPxUOMQty() {
    return pxUOMQty;
  }

  /**
   * Sets the value of the pxUOMQty property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPxUOMQty(BigDecimal value) {
    this.pxUOMQty = value;
  }

  /**
   * Gets the value of the pxUOMCcy property.
   *
   * @return possible object is {@link String }
   */
  public String getPxUOMCcy() {
    return pxUOMCcy;
  }

  /**
   * Sets the value of the pxUOMCcy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPxUOMCcy(String value) {
    this.pxUOMCcy = value;
  }

  /**
   * Gets the value of the tmUnit property.
   *
   * @return possible object is {@link TimeUnitEnumT }
   */
  public TimeUnitEnumT getTmUnit() {
    return tmUnit;
  }

  /**
   * Sets the value of the tmUnit property.
   *
   * @param value allowed object is {@link TimeUnitEnumT }
   */
  public void setTmUnit(TimeUnitEnumT value) {
    this.tmUnit = value;
  }

  /**
   * Gets the value of the exerStyle property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getExerStyle() {
    return exerStyle;
  }

  /**
   * Sets the value of the exerStyle property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setExerStyle(BigInteger value) {
    this.exerStyle = value;
  }

  /**
   * Gets the value of the pxQteCcy property.
   *
   * @return possible object is {@link String }
   */
  public String getPxQteCcy() {
    return pxQteCcy;
  }

  /**
   * Sets the value of the pxQteCcy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPxQteCcy(String value) {
    this.pxQteCcy = value;
  }

  /**
   * Gets the value of the cpnRt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCpnRt() {
    return cpnRt;
  }

  /**
   * Sets the value of the cpnRt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCpnRt(BigDecimal value) {
    this.cpnRt = value;
  }

  /**
   * Gets the value of the exch property.
   *
   * @return possible object is {@link String }
   */
  public String getExch() {
    return exch;
  }

  /**
   * Sets the value of the exch property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExch(String value) {
    this.exch = value;
  }

  /**
   * Gets the value of the issr property.
   *
   * @return possible object is {@link String }
   */
  public String getIssr() {
    return issr;
  }

  /**
   * Sets the value of the issr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIssr(String value) {
    this.issr = value;
  }

  /**
   * Gets the value of the encUndIssrLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncUndIssrLen() {
    return encUndIssrLen;
  }

  /**
   * Sets the value of the encUndIssrLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncUndIssrLen(BigInteger value) {
    this.encUndIssrLen = value;
  }

  /**
   * Gets the value of the encUndIssr property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncUndIssr() {
    return encUndIssr;
  }

  /**
   * Sets the value of the encUndIssr property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncUndIssr(byte[] value) {
    this.encUndIssr = value;
  }

  /**
   * Gets the value of the shrtName property.
   *
   * @return possible object is {@link String }
   */
  public String getShrtName() {
    return shrtName;
  }

  /**
   * Sets the value of the shrtName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setShrtName(String value) {
    this.shrtName = value;
  }

  /**
   * Gets the value of the fullName property.
   *
   * @return possible object is {@link String }
   */
  public String getFullName() {
    return fullName;
  }

  /**
   * Sets the value of the fullName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFullName(String value) {
    this.fullName = value;
  }

  /**
   * Gets the value of the encFullNameLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncFullNameLen() {
    return encFullNameLen;
  }

  /**
   * Sets the value of the encFullNameLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncFullNameLen(BigInteger value) {
    this.encFullNameLen = value;
  }

  /**
   * Gets the value of the encFullName property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncFullName() {
    return encFullName;
  }

  /**
   * Sets the value of the encFullName property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncFullName(byte[] value) {
    this.encFullName = value;
  }

  /**
   * Gets the value of the ndxUnit property.
   *
   * @return possible object is {@link PaymentStreamRateIndexCurveUnitEnumT }
   */
  public PaymentStreamRateIndexCurveUnitEnumT getNdxUnit() {
    return ndxUnit;
  }

  /**
   * Sets the value of the ndxUnit property.
   *
   * @param value allowed object is {@link PaymentStreamRateIndexCurveUnitEnumT }
   */
  public void setNdxUnit(PaymentStreamRateIndexCurveUnitEnumT value) {
    this.ndxUnit = value;
  }

  /**
   * Gets the value of the ndxPeriod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNdxPeriod() {
    return ndxPeriod;
  }

  /**
   * Sets the value of the ndxPeriod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNdxPeriod(BigInteger value) {
    this.ndxPeriod = value;
  }

  /**
   * Gets the value of the desc property.
   *
   * @return possible object is {@link String }
   */
  public String getDesc() {
    return desc;
  }

  /**
   * Sets the value of the desc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDesc(String value) {
    this.desc = value;
  }

  /**
   * Gets the value of the encUndSecDescLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncUndSecDescLen() {
    return encUndSecDescLen;
  }

  /**
   * Sets the value of the encUndSecDescLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncUndSecDescLen(BigInteger value) {
    this.encUndSecDescLen = value;
  }

  /**
   * Gets the value of the encUndSecDesc property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncUndSecDesc() {
    return encUndSecDesc;
  }

  /**
   * Sets the value of the encUndSecDesc property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncUndSecDesc(byte[] value) {
    this.encUndSecDesc = value;
  }

  /**
   * Gets the value of the cpPgm property.
   *
   * @return possible object is {@link String }
   */
  public String getCPPgm() {
    return cpPgm;
  }

  /**
   * Sets the value of the cpPgm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCPPgm(String value) {
    this.cpPgm = value;
  }

  /**
   * Gets the value of the cpRegTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getCPRegTyp() {
    return cpRegTyp;
  }

  /**
   * Sets the value of the cpRegTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCPRegTyp(String value) {
    this.cpRegTyp = value;
  }

  /**
   * Gets the value of the allocPct property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getAllocPct() {
    return allocPct;
  }

  /**
   * Sets the value of the allocPct property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setAllocPct(BigDecimal value) {
    this.allocPct = value;
  }

  /**
   * Gets the value of the ccy property.
   *
   * @return possible object is {@link String }
   */
  public String getCcy() {
    return ccy;
  }

  /**
   * Sets the value of the ccy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCcy(String value) {
    this.ccy = value;
  }

  /**
   * Gets the value of the qty property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getQty() {
    return qty;
  }

  /**
   * Sets the value of the qty property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setQty(BigDecimal value) {
    this.qty = value;
  }

  /**
   * Gets the value of the settlTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getSettlTyp() {
    return settlTyp;
  }

  /**
   * Sets the value of the settlTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setSettlTyp(BigInteger value) {
    this.settlTyp = value;
  }

  /**
   * Gets the value of the cashAmt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCashAmt() {
    return cashAmt;
  }

  /**
   * Sets the value of the cashAmt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCashAmt(BigDecimal value) {
    this.cashAmt = value;
  }

  /**
   * Gets the value of the cashTyp property.
   *
   * @return possible object is {@link UnderlyingCashTypeEnumT }
   */
  public UnderlyingCashTypeEnumT getCashTyp() {
    return cashTyp;
  }

  /**
   * Sets the value of the cashTyp property.
   *
   * @param value allowed object is {@link UnderlyingCashTypeEnumT }
   */
  public void setCashTyp(UnderlyingCashTypeEnumT value) {
    this.cashTyp = value;
  }

  /**
   * Gets the value of the px property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPx() {
    return px;
  }

  /**
   * Sets the value of the px property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPx(BigDecimal value) {
    this.px = value;
  }

  /**
   * Gets the value of the dirtPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getDirtPx() {
    return dirtPx;
  }

  /**
   * Sets the value of the dirtPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setDirtPx(BigDecimal value) {
    this.dirtPx = value;
  }

  /**
   * Gets the value of the endPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getEndPx() {
    return endPx;
  }

  /**
   * Sets the value of the endPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setEndPx(BigDecimal value) {
    this.endPx = value;
  }

  /**
   * Gets the value of the startVal property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStartVal() {
    return startVal;
  }

  /**
   * Sets the value of the startVal property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStartVal(BigDecimal value) {
    this.startVal = value;
  }

  /**
   * Gets the value of the curVal property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCurVal() {
    return curVal;
  }

  /**
   * Sets the value of the curVal property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCurVal(BigDecimal value) {
    this.curVal = value;
  }

  /**
   * Gets the value of the endVal property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getEndVal() {
    return endVal;
  }

  /**
   * Sets the value of the endVal property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setEndVal(BigDecimal value) {
    this.endVal = value;
  }

  /**
   * Gets the value of the adjQty property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getAdjQty() {
    return adjQty;
  }

  /**
   * Sets the value of the adjQty property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setAdjQty(BigDecimal value) {
    this.adjQty = value;
  }

  /**
   * Gets the value of the fxRate property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getFxRate() {
    return fxRate;
  }

  /**
   * Sets the value of the fxRate property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setFxRate(BigDecimal value) {
    this.fxRate = value;
  }

  /**
   * Gets the value of the fxRateCalc property.
   *
   * @return possible object is {@link UnderlyingFXRateCalcEnumT }
   */
  public UnderlyingFXRateCalcEnumT getFxRateCalc() {
    return fxRateCalc;
  }

  /**
   * Sets the value of the fxRateCalc property.
   *
   * @param value allowed object is {@link UnderlyingFXRateCalcEnumT }
   */
  public void setFxRateCalc(UnderlyingFXRateCalcEnumT value) {
    this.fxRateCalc = value;
  }

  /**
   * Gets the value of the capValu property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCapValu() {
    return capValu;
  }

  /**
   * Sets the value of the capValu property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCapValu(BigDecimal value) {
    this.capValu = value;
  }

  /**
   * Gets the value of the setMeth property.
   *
   * @return possible object is {@link SettlMethodEnumT }
   */
  public SettlMethodEnumT getSetMeth() {
    return setMeth;
  }

  /**
   * Sets the value of the setMeth property.
   *
   * @param value allowed object is {@link SettlMethodEnumT }
   */
  public void setSetMeth(SettlMethodEnumT value) {
    this.setMeth = value;
  }

  /**
   * Gets the value of the putCall property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPutCall() {
    return putCall;
  }

  /**
   * Sets the value of the putCall property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPutCall(BigInteger value) {
    this.putCall = value;
  }

  /**
   * Gets the value of the itmCond property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getITMCond() {
    return itmCond;
  }

  /**
   * Sets the value of the itmCond property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setITMCond(BigInteger value) {
    this.itmCond = value;
  }

  /**
   * Gets the value of the cntraryInstEligInd property.
   *
   * @return possible object is {@link String }
   */
  public String getCntraryInstEligInd() {
    return cntraryInstEligInd;
  }

  /**
   * Sets the value of the cntraryInstEligInd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCntraryInstEligInd(String value) {
    this.cntraryInstEligInd = value;
  }

  /**
   * Gets the value of the constuentWt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getConstuentWt() {
    return constuentWt;
  }

  /**
   * Sets the value of the constuentWt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setConstuentWt(BigDecimal value) {
    this.constuentWt = value;
  }

  /**
   * Gets the value of the cpnTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getCpnTyp() {
    return cpnTyp;
  }

  /**
   * Sets the value of the cpnTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setCpnTyp(BigInteger value) {
    this.cpnTyp = value;
  }

  /**
   * Gets the value of the totIssuedAmt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getTotIssuedAmt() {
    return totIssuedAmt;
  }

  /**
   * Sets the value of the totIssuedAmt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setTotIssuedAmt(BigDecimal value) {
    this.totIssuedAmt = value;
  }

  /**
   * Gets the value of the cpnPeriod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getCpnPeriod() {
    return cpnPeriod;
  }

  /**
   * Sets the value of the cpnPeriod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setCpnPeriod(BigInteger value) {
    this.cpnPeriod = value;
  }

  /**
   * Gets the value of the cpnUnit property.
   *
   * @return possible object is {@link CouponFrequencyUnitEnumT }
   */
  public CouponFrequencyUnitEnumT getCpnUnit() {
    return cpnUnit;
  }

  /**
   * Sets the value of the cpnUnit property.
   *
   * @param value allowed object is {@link CouponFrequencyUnitEnumT }
   */
  public void setCpnUnit(CouponFrequencyUnitEnumT value) {
    this.cpnUnit = value;
  }

  /**
   * Gets the value of the cpnDayCnt property.
   *
   * @return possible object is {@link String }
   */
  public String getCpnDayCnt() {
    return cpnDayCnt;
  }

  /**
   * Sets the value of the cpnDayCnt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCpnDayCnt(String value) {
    this.cpnDayCnt = value;
  }

  /**
   * Gets the value of the obligID property.
   *
   * @return possible object is {@link String }
   */
  public String getObligID() {
    return obligID;
  }

  /**
   * Sets the value of the obligID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setObligID(String value) {
    this.obligID = value;
  }

  /**
   * Gets the value of the obligIDSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getObligIDSrc() {
    return obligIDSrc;
  }

  /**
   * Sets the value of the obligIDSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setObligIDSrc(String value) {
    this.obligIDSrc = value;
  }

  /**
   * Gets the value of the eqtyID property.
   *
   * @return possible object is {@link String }
   */
  public String getEqtyID() {
    return eqtyID;
  }

  /**
   * Sets the value of the eqtyID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEqtyID(String value) {
    this.eqtyID = value;
  }

  /**
   * Gets the value of the eqtyIDSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getEqtyIDSrc() {
    return eqtyIDSrc;
  }

  /**
   * Sets the value of the eqtyIDSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEqtyIDSrc(String value) {
    this.eqtyIDSrc = value;
  }

  /**
   * Gets the value of the futID property.
   *
   * @return possible object is {@link String }
   */
  public String getFutID() {
    return futID;
  }

  /**
   * Sets the value of the futID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFutID(String value) {
    this.futID = value;
  }

  /**
   * Gets the value of the futIDSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getFutIDSrc() {
    return futIDSrc;
  }

  /**
   * Sets the value of the futIDSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFutIDSrc(String value) {
    this.futIDSrc = value;
  }

  /**
   * Gets the value of the lienSnrty property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getLienSnrty() {
    return lienSnrty;
  }

  /**
   * Sets the value of the lienSnrty property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setLienSnrty(BigInteger value) {
    this.lienSnrty = value;
  }

  /**
   * Gets the value of the loanFclty property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getLoanFclty() {
    return loanFclty;
  }

  /**
   * Sets the value of the loanFclty property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setLoanFclty(BigInteger value) {
    this.loanFclty = value;
  }

  /**
   * Gets the value of the refEntityTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRefEntityTyp() {
    return refEntityTyp;
  }

  /**
   * Sets the value of the refEntityTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRefEntityTyp(BigInteger value) {
    this.refEntityTyp = value;
  }

  /**
   * Gets the value of the ndxSeries property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNdxSeries() {
    return ndxSeries;
  }

  /**
   * Sets the value of the ndxSeries property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNdxSeries(BigInteger value) {
    this.ndxSeries = value;
  }

  /**
   * Gets the value of the ndxAnxVer property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNdxAnxVer() {
    return ndxAnxVer;
  }

  /**
   * Sets the value of the ndxAnxVer property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNdxAnxVer(BigInteger value) {
    this.ndxAnxVer = value;
  }

  /**
   * Gets the value of the ndxAnxDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getNdxAnxDt() {
    return ndxAnxDt;
  }

  /**
   * Sets the value of the ndxAnxDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setNdxAnxDt(XMLGregorianCalendar value) {
    this.ndxAnxDt = value;
  }

  /**
   * Gets the value of the ndxAnxSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getNdxAnxSrc() {
    return ndxAnxSrc;
  }

  /**
   * Sets the value of the ndxAnxSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNdxAnxSrc(String value) {
    this.ndxAnxSrc = value;
  }

  /**
   * Gets the value of the settlNdx property.
   *
   * @return possible object is {@link String }
   */
  public String getSettlNdx() {
    return settlNdx;
  }

  /**
   * Sets the value of the settlNdx property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSettlNdx(String value) {
    this.settlNdx = value;
  }

  /**
   * Gets the value of the settlNdxLctn property.
   *
   * @return possible object is {@link String }
   */
  public String getSettlNdxLctn() {
    return settlNdxLctn;
  }

  /**
   * Sets the value of the settlNdxLctn property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSettlNdxLctn(String value) {
    this.settlNdxLctn = value;
  }

  /**
   * Gets the value of the expDesc property.
   *
   * @return possible object is {@link String }
   */
  public String getExpDesc() {
    return expDesc;
  }

  /**
   * Sets the value of the expDesc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExpDesc(String value) {
    this.expDesc = value;
  }

  /**
   * Gets the value of the encExpDescLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncExpDescLen() {
    return encExpDescLen;
  }

  /**
   * Sets the value of the encExpDescLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncExpDescLen(BigInteger value) {
    this.encExpDescLen = value;
  }

  /**
   * Gets the value of the encExpDesc property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncExpDesc() {
    return encExpDesc;
  }

  /**
   * Sets the value of the encExpDesc property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncExpDesc(byte[] value) {
    this.encExpDesc = value;
  }

  /**
   * Gets the value of the prodCmplx property.
   *
   * @return possible object is {@link String }
   */
  public String getProdCmplx() {
    return prodCmplx;
  }

  /**
   * Sets the value of the prodCmplx property.
   *
   * @param value allowed object is {@link String }
   */
  public void setProdCmplx(String value) {
    this.prodCmplx = value;
  }

  /**
   * Gets the value of the secGrp property.
   *
   * @return possible object is {@link String }
   */
  public String getSecGrp() {
    return secGrp;
  }

  /**
   * Sets the value of the secGrp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSecGrp(String value) {
    this.secGrp = value;
  }

  /**
   * Gets the value of the settlOnOpenFlag property.
   *
   * @return possible object is {@link String }
   */
  public String getSettlOnOpenFlag() {
    return settlOnOpenFlag;
  }

  /**
   * Sets the value of the settlOnOpenFlag property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSettlOnOpenFlag(String value) {
    this.settlOnOpenFlag = value;
  }

  /**
   * Gets the value of the asgnMeth property.
   *
   * @return possible object is {@link InstrmtAssignmentMethodEnumT }
   */
  public InstrmtAssignmentMethodEnumT getAsgnMeth() {
    return asgnMeth;
  }

  /**
   * Sets the value of the asgnMeth property.
   *
   * @param value allowed object is {@link InstrmtAssignmentMethodEnumT }
   */
  public void setAsgnMeth(InstrmtAssignmentMethodEnumT value) {
    this.asgnMeth = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return possible object is {@link String }
   */
  public String getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStatus(String value) {
    this.status = value;
  }

  /**
   * Gets the value of the obligTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getObligTyp() {
    return obligTyp;
  }

  /**
   * Sets the value of the obligTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setObligTyp(String value) {
    this.obligTyp = value;
  }

  /**
   * Gets the value of the assetGrp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getAssetGrp() {
    return assetGrp;
  }

  /**
   * Sets the value of the assetGrp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setAssetGrp(BigInteger value) {
    this.assetGrp = value;
  }

  /**
   * Gets the value of the assetClss property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getAssetClss() {
    return assetClss;
  }

  /**
   * Sets the value of the assetClss property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setAssetClss(BigInteger value) {
    this.assetClss = value;
  }

  /**
   * Gets the value of the assetSubClss property.
   *
   * @return possible object is {@link String }
   */
  public String getAssetSubClss() {
    return assetSubClss;
  }

  /**
   * Sets the value of the assetSubClss property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAssetSubClss(String value) {
    this.assetSubClss = value;
  }

  /**
   * Gets the value of the assetTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getAssetTyp() {
    return assetTyp;
  }

  /**
   * Sets the value of the assetTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAssetTyp(String value) {
    this.assetTyp = value;
  }

  /**
   * Gets the value of the asstSubTyp property.
   *
   * @return possible object is {@link String }
   */
  public String getAsstSubTyp() {
    return asstSubTyp;
  }

  /**
   * Sets the value of the asstSubTyp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAsstSubTyp(String value) {
    this.asstSubTyp = value;
  }

  /**
   * Gets the value of the swapClss property.
   *
   * @return possible object is {@link SwapClassEnumT }
   */
  public SwapClassEnumT getSwapClss() {
    return swapClss;
  }

  /**
   * Sets the value of the swapClss property.
   *
   * @param value allowed object is {@link SwapClassEnumT }
   */
  public void setSwapClss(SwapClassEnumT value) {
    this.swapClss = value;
  }

  /**
   * Gets the value of the swapSubClss property.
   *
   * @return possible object is {@link SwapSubClassEnumT }
   */
  public SwapSubClassEnumT getSwapSubClss() {
    return swapSubClss;
  }

  /**
   * Sets the value of the swapSubClss property.
   *
   * @param value allowed object is {@link SwapSubClassEnumT }
   */
  public void setSwapSubClss(SwapSubClassEnumT value) {
    this.swapSubClss = value;
  }

  /**
   * Gets the value of the nthDflt property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNthDflt() {
    return nthDflt;
  }

  /**
   * Sets the value of the nthDflt property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNthDflt(BigInteger value) {
    this.nthDflt = value;
  }

  /**
   * Gets the value of the mthDflt property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMthDflt() {
    return mthDflt;
  }

  /**
   * Sets the value of the mthDflt property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMthDflt(BigInteger value) {
    this.mthDflt = value;
  }

  /**
   * Gets the value of the settldMtrxSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getSettldMtrxSrc() {
    return settldMtrxSrc;
  }

  /**
   * Sets the value of the settldMtrxSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSettldMtrxSrc(String value) {
    this.settldMtrxSrc = value;
  }

  /**
   * Gets the value of the settldMtrxDt property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getSettldMtrxDt() {
    return settldMtrxDt;
  }

  /**
   * Sets the value of the settldMtrxDt property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setSettldMtrxDt(XMLGregorianCalendar value) {
    this.settldMtrxDt = value;
  }

  /**
   * Gets the value of the strkMult property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkMult() {
    return strkMult;
  }

  /**
   * Sets the value of the strkMult property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkMult(BigDecimal value) {
    this.strkMult = value;
  }

  /**
   * Gets the value of the strkValu property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkValu() {
    return strkValu;
  }

  /**
   * Sets the value of the strkValu property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkValu(BigDecimal value) {
    this.strkValu = value;
  }

  /**
   * Gets the value of the strkUOM property.
   *
   * @return possible object is {@link UnitOfMeasureEnumT }
   */
  public UnitOfMeasureEnumT getStrkUOM() {
    return strkUOM;
  }

  /**
   * Sets the value of the strkUOM property.
   *
   * @param value allowed object is {@link UnitOfMeasureEnumT }
   */
  public void setStrkUOM(UnitOfMeasureEnumT value) {
    this.strkUOM = value;
  }

  /**
   * Gets the value of the strkNdxPnt property.
   *
   * @return possible object is {@link String }
   */
  public String getStrkNdxPnt() {
    return strkNdxPnt;
  }

  /**
   * Sets the value of the strkNdxPnt property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStrkNdxPnt(String value) {
    this.strkNdxPnt = value;
  }

  /**
   * Gets the value of the strkNdx property.
   *
   * @return possible object is {@link String }
   */
  public String getStrkNdx() {
    return strkNdx;
  }

  /**
   * Sets the value of the strkNdx property.
   *
   * @param value allowed object is {@link String }
   */
  public void setStrkNdx(String value) {
    this.strkNdx = value;
  }

  /**
   * Gets the value of the strkNdxQte property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getStrkNdxQte() {
    return strkNdxQte;
  }

  /**
   * Sets the value of the strkNdxQte property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setStrkNdxQte(BigInteger value) {
    this.strkNdxQte = value;
  }

  /**
   * Gets the value of the strkSpread property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkSpread() {
    return strkSpread;
  }

  /**
   * Sets the value of the strkSpread property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkSpread(BigDecimal value) {
    this.strkSpread = value;
  }

  /**
   * Gets the value of the strkPxDtrmnMeth property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getStrkPxDtrmnMeth() {
    return strkPxDtrmnMeth;
  }

  /**
   * Sets the value of the strkPxDtrmnMeth property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setStrkPxDtrmnMeth(BigInteger value) {
    this.strkPxDtrmnMeth = value;
  }

  /**
   * Gets the value of the strkPxBndryMeth property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getStrkPxBndryMeth() {
    return strkPxBndryMeth;
  }

  /**
   * Sets the value of the strkPxBndryMeth property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setStrkPxBndryMeth(BigInteger value) {
    this.strkPxBndryMeth = value;
  }

  /**
   * Gets the value of the strkPxBndryPrcsn property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getStrkPxBndryPrcsn() {
    return strkPxBndryPrcsn;
  }

  /**
   * Sets the value of the strkPxBndryPrcsn property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setStrkPxBndryPrcsn(BigDecimal value) {
    this.strkPxBndryPrcsn = value;
  }

  /**
   * Gets the value of the minPxIncr property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getMinPxIncr() {
    return minPxIncr;
  }

  /**
   * Sets the value of the minPxIncr property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setMinPxIncr(BigDecimal value) {
    this.minPxIncr = value;
  }

  /**
   * Gets the value of the minPxIncrAmt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getMinPxIncrAmt() {
    return minPxIncrAmt;
  }

  /**
   * Sets the value of the minPxIncrAmt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setMinPxIncrAmt(BigDecimal value) {
    this.minPxIncrAmt = value;
  }

  /**
   * Gets the value of the optPayoutTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getOptPayoutTyp() {
    return optPayoutTyp;
  }

  /**
   * Sets the value of the optPayoutTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setOptPayoutTyp(BigInteger value) {
    this.optPayoutTyp = value;
  }

  /**
   * Gets the value of the optPayAmt property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getOptPayAmt() {
    return optPayAmt;
  }

  /**
   * Sets the value of the optPayAmt property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setOptPayAmt(BigDecimal value) {
    this.optPayAmt = value;
  }

  /**
   * Gets the value of the rtnTrgr property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRtnTrgr() {
    return rtnTrgr;
  }

  /**
   * Sets the value of the rtnTrgr property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRtnTrgr(BigInteger value) {
    this.rtnTrgr = value;
  }

  /**
   * Gets the value of the pxQteMeth property.
   *
   * @return possible object is {@link PriceQuoteMethodEnumT }
   */
  public PriceQuoteMethodEnumT getPxQteMeth() {
    return pxQteMeth;
  }

  /**
   * Sets the value of the pxQteMeth property.
   *
   * @param value allowed object is {@link PriceQuoteMethodEnumT }
   */
  public void setPxQteMeth(PriceQuoteMethodEnumT value) {
    this.pxQteMeth = value;
  }

  /**
   * Gets the value of the valMeth property.
   *
   * @return possible object is {@link ValuationMethodEnumT }
   */
  public ValuationMethodEnumT getValMeth() {
    return valMeth;
  }

  /**
   * Sets the value of the valMeth property.
   *
   * @param value allowed object is {@link ValuationMethodEnumT }
   */
  public void setValMeth(ValuationMethodEnumT value) {
    this.valMeth = value;
  }

  /**
   * Gets the value of the valSrc property.
   *
   * @return possible object is {@link String }
   */
  public String getValSrc() {
    return valSrc;
  }

  /**
   * Sets the value of the valSrc property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValSrc(String value) {
    this.valSrc = value;
  }

  /**
   * Gets the value of the valRefModel property.
   *
   * @return possible object is {@link String }
   */
  public String getValRefModel() {
    return valRefModel;
  }

  /**
   * Sets the value of the valRefModel property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValRefModel(String value) {
    this.valRefModel = value;
  }

  /**
   * Gets the value of the listMeth property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getListMeth() {
    return listMeth;
  }

  /**
   * Sets the value of the listMeth property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setListMeth(BigInteger value) {
    this.listMeth = value;
  }

  /**
   * Gets the value of the capPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCapPx() {
    return capPx;
  }

  /**
   * Sets the value of the capPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCapPx(BigDecimal value) {
    this.capPx = value;
  }

  /**
   * Gets the value of the flrPx property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getFlrPx() {
    return flrPx;
  }

  /**
   * Sets the value of the flrPx property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setFlrPx(BigDecimal value) {
    this.flrPx = value;
  }

  /**
   * Gets the value of the flexInd property.
   *
   * @return possible object is {@link String }
   */
  public String getFlexInd() {
    return flexInd;
  }

  /**
   * Sets the value of the flexInd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFlexInd(String value) {
    this.flexInd = value;
  }

  /**
   * Gets the value of the flexProdElig property.
   *
   * @return possible object is {@link String }
   */
  public String getFlexProdElig() {
    return flexProdElig;
  }

  /**
   * Sets the value of the flexProdElig property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFlexProdElig(String value) {
    this.flexProdElig = value;
  }

  /**
   * Gets the value of the posLmt property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getPosLmt() {
    return posLmt;
  }

  /**
   * Sets the value of the posLmt property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setPosLmt(BigInteger value) {
    this.posLmt = value;
  }

  /**
   * Gets the value of the ntPosLmt property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getNTPosLmt() {
    return ntPosLmt;
  }

  /**
   * Sets the value of the ntPosLmt property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setNTPosLmt(BigInteger value) {
    this.ntPosLmt = value;
  }

  /**
   * Gets the value of the pool property.
   *
   * @return possible object is {@link String }
   */
  public String getPool() {
    return pool;
  }

  /**
   * Sets the value of the pool property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPool(String value) {
    this.pool = value;
  }

  /**
   * Gets the value of the cSetMo property.
   *
   * @return possible object is {@link String }
   */
  public String getCSetMo() {
    return cSetMo;
  }

  /**
   * Sets the value of the cSetMo property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCSetMo(String value) {
    this.cSetMo = value;
  }

  /**
   * Gets the value of the dated property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDated() {
    return dated;
  }

  /**
   * Sets the value of the dated property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDated(XMLGregorianCalendar value) {
    this.dated = value;
  }

  /**
   * Gets the value of the intAcrl property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getIntAcrl() {
    return intAcrl;
  }

  /**
   * Sets the value of the intAcrl property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setIntAcrl(XMLGregorianCalendar value) {
    this.intAcrl = value;
  }

  /**
   * Gets the value of the shrtRstctn property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getShrtRstctn() {
    return shrtRstctn;
  }

  /**
   * Sets the value of the shrtRstctn property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setShrtRstctn(BigInteger value) {
    this.shrtRstctn = value;
  }

  /**
   * Gets the value of the refTickTblID property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRefTickTblID() {
    return refTickTblID;
  }

  /**
   * Sets the value of the refTickTblID property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRefTickTblID(BigInteger value) {
    this.refTickTblID = value;
  }

  /**
   * Gets the value of the protctnXIDRef property.
   *
   * @return possible object is {@link Object }
   */
  public Object getProtctnXIDRef() {
    return protctnXIDRef;
  }

  /**
   * Sets the value of the protctnXIDRef property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setProtctnXIDRef(Object value) {
    this.protctnXIDRef = value;
  }

  /**
   * Gets the value of the settlXIDRef property.
   *
   * @return possible object is {@link Object }
   */
  public Object getSettlXIDRef() {
    return settlXIDRef;
  }

  /**
   * Sets the value of the settlXIDRef property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setSettlXIDRef(Object value) {
    this.settlXIDRef = value;
  }

  /**
   * Gets the value of the strtTyp property.
   *
   * @return possible object is {@link StrategyTypeEnumT }
   */
  public StrategyTypeEnumT getStrtTyp() {
    return strtTyp;
  }

  /**
   * Sets the value of the strtTyp property.
   *
   * @param value allowed object is {@link StrategyTypeEnumT }
   */
  public void setStrtTyp(StrategyTypeEnumT value) {
    this.strtTyp = value;
  }

  /**
   * Gets the value of the cmnPxng property.
   *
   * @return possible object is {@link String }
   */
  public String getCmnPxng() {
    return cmnPxng;
  }

  /**
   * Sets the value of the cmnPxng property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCmnPxng(String value) {
    this.cmnPxng = value;
  }

  /**
   * Gets the value of the settlDsrptnProv property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getSettlDsrptnProv() {
    return settlDsrptnProv;
  }

  /**
   * Sets the value of the settlDsrptnProv property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setSettlDsrptnProv(BigInteger value) {
    this.settlDsrptnProv = value;
  }

  /**
   * Gets the value of the rteChrtr property.
   *
   * @return possible object is {@link String }
   */
  public String getRteChrtr() {
    return rteChrtr;
  }

  /**
   * Sets the value of the rteChrtr property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRteChrtr(String value) {
    this.rteChrtr = value;
  }

  /**
   * Gets the value of the rndDirctn property.
   *
   * @return possible object is {@link String }
   */
  public String getRndDirctn() {
    return rndDirctn;
  }

  /**
   * Sets the value of the rndDirctn property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRndDirctn(String value) {
    this.rndDirctn = value;
  }

  /**
   * Gets the value of the rndPrcsn property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRndPrcsn() {
    return rndPrcsn;
  }

  /**
   * Sets the value of the rndPrcsn property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRndPrcsn(BigInteger value) {
    this.rndPrcsn = value;
  }

  /**
   * Gets the value of the extrordEvntAdjMeth property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getExtrordEvntAdjMeth() {
    return extrordEvntAdjMeth;
  }

  /**
   * Sets the value of the extrordEvntAdjMeth property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setExtrordEvntAdjMeth(BigInteger value) {
    this.extrordEvntAdjMeth = value;
  }

  /**
   * Gets the value of the exchLookAlike property.
   *
   * @return possible object is {@link String }
   */
  public String getExchLookAlike() {
    return exchLookAlike;
  }

  /**
   * Sets the value of the exchLookAlike property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExchLookAlike(String value) {
    this.exchLookAlike = value;
  }

  /**
   * Gets the value of the avgLmtPctg property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getAvgLmtPctg() {
    return avgLmtPctg;
  }

  /**
   * Sets the value of the avgLmtPctg property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setAvgLmtPctg(BigDecimal value) {
    this.avgLmtPctg = value;
  }

  /**
   * Gets the value of the avgLmtDys property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getAvgLmtDys() {
    return avgLmtDys;
  }

  /**
   * Sets the value of the avgLmtDys property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setAvgLmtDys(BigInteger value) {
    this.avgLmtDys = value;
  }

  /**
   * Gets the value of the dpstryRcptInd property.
   *
   * @return possible object is {@link String }
   */
  public String getDpstryRcptInd() {
    return dpstryRcptInd;
  }

  /**
   * Sets the value of the dpstryRcptInd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDpstryRcptInd(String value) {
    this.dpstryRcptInd = value;
  }

  /**
   * Gets the value of the opnUnits property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getOpnUnits() {
    return opnUnits;
  }

  /**
   * Sets the value of the opnUnits property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setOpnUnits(BigDecimal value) {
    this.opnUnits = value;
  }

  /**
   * Gets the value of the bsktDvsr property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getBsktDvsr() {
    return bsktDvsr;
  }

  /**
   * Sets the value of the bsktDvsr property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setBsktDvsr(BigDecimal value) {
    this.bsktDvsr = value;
  }

  /**
   * Gets the value of the xid property.
   *
   * @return possible object is {@link String }
   */
  public String getXID() {
    return xid;
  }

  /**
   * Sets the value of the xid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setXID(String value) {
    this.xid = value;
  }
}
