//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.04 at 04:33:21 PM IST
//

package com.deloitte.sample.integration.demo.publisher.transformation.fixml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;

/**
 * UserRequest can be found in Volume 1 of the specification
 *
 * <p>Java class for UserRequest_message_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UserRequest_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/FIXML-5-0-SP2}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UserRequestElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}UserRequestAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserRequest_message_t")
public class UserRequestMessageT extends AbstractMessageT {

  @XmlAttribute(name = "UserReqID", required = true)
  protected String userReqID;

  @XmlAttribute(name = "UserReqTyp", required = true)
  protected BigInteger userReqTyp;

  @XmlAttribute(name = "Username", required = true)
  protected String username;

  @XmlAttribute(name = "Password")
  protected String password;

  @XmlAttribute(name = "NewPassword")
  protected String newPassword;

  @XmlAttribute(name = "EncPwdMethod")
  protected BigInteger encPwdMethod;

  @XmlAttribute(name = "EncPwdLen")
  protected BigInteger encPwdLen;

  @XmlAttribute(name = "EncPwd")
  protected byte[] encPwd;

  @XmlAttribute(name = "EncNewPwdLen")
  protected BigInteger encNewPwdLen;

  @XmlAttribute(name = "EncNewPwd")
  protected byte[] encNewPwd;

  @XmlAttribute(name = "RawDataLength")
  protected BigInteger rawDataLength;

  @XmlAttribute(name = "RawData")
  protected byte[] rawData;

  /**
   * Gets the value of the userReqID property.
   *
   * @return possible object is {@link String }
   */
  public String getUserReqID() {
    return userReqID;
  }

  /**
   * Sets the value of the userReqID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUserReqID(String value) {
    this.userReqID = value;
  }

  /**
   * Gets the value of the userReqTyp property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getUserReqTyp() {
    return userReqTyp;
  }

  /**
   * Sets the value of the userReqTyp property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setUserReqTyp(BigInteger value) {
    this.userReqTyp = value;
  }

  /**
   * Gets the value of the username property.
   *
   * @return possible object is {@link String }
   */
  public String getUsername() {
    return username;
  }

  /**
   * Sets the value of the username property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUsername(String value) {
    this.username = value;
  }

  /**
   * Gets the value of the password property.
   *
   * @return possible object is {@link String }
   */
  public String getPassword() {
    return password;
  }

  /**
   * Sets the value of the password property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPassword(String value) {
    this.password = value;
  }

  /**
   * Gets the value of the newPassword property.
   *
   * @return possible object is {@link String }
   */
  public String getNewPassword() {
    return newPassword;
  }

  /**
   * Sets the value of the newPassword property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNewPassword(String value) {
    this.newPassword = value;
  }

  /**
   * Gets the value of the encPwdMethod property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncPwdMethod() {
    return encPwdMethod;
  }

  /**
   * Sets the value of the encPwdMethod property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncPwdMethod(BigInteger value) {
    this.encPwdMethod = value;
  }

  /**
   * Gets the value of the encPwdLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncPwdLen() {
    return encPwdLen;
  }

  /**
   * Sets the value of the encPwdLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncPwdLen(BigInteger value) {
    this.encPwdLen = value;
  }

  /**
   * Gets the value of the encPwd property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncPwd() {
    return encPwd;
  }

  /**
   * Sets the value of the encPwd property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncPwd(byte[] value) {
    this.encPwd = value;
  }

  /**
   * Gets the value of the encNewPwdLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getEncNewPwdLen() {
    return encNewPwdLen;
  }

  /**
   * Sets the value of the encNewPwdLen property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setEncNewPwdLen(BigInteger value) {
    this.encNewPwdLen = value;
  }

  /**
   * Gets the value of the encNewPwd property.
   *
   * @return possible object is byte[]
   */
  public byte[] getEncNewPwd() {
    return encNewPwd;
  }

  /**
   * Sets the value of the encNewPwd property.
   *
   * @param value allowed object is byte[]
   */
  public void setEncNewPwd(byte[] value) {
    this.encNewPwd = value;
  }

  /**
   * Gets the value of the rawDataLength property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRawDataLength() {
    return rawDataLength;
  }

  /**
   * Sets the value of the rawDataLength property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRawDataLength(BigInteger value) {
    this.rawDataLength = value;
  }

  /**
   * Gets the value of the rawData property.
   *
   * @return possible object is byte[]
   */
  public byte[] getRawData() {
    return rawData;
  }

  /**
   * Sets the value of the rawData property.
   *
   * @param value allowed object is byte[]
   */
  public void setRawData(byte[] value) {
    this.rawData = value;
  }
}
